// ─── Imported task seeds ─────────────────────────────────────────────────────
// Source: "Venture Task Tracker.xlsx" (3 brand sheets, 47 tasks), imported
// 2026-08-25. Each task keeps its original free-text status verbatim in
// `status`; `column` is that status mapped onto the kanban lanes.
//
// The spreadsheet has no priority column, so every imported task is seeded at
// medium weight rather than inventing a priority. Resource links that were
// bare row numbers instead of URLs were dropped, not kept as fake links.
//
// These seeds show only until someone saves that board; after the first save
// the server copy wins (same contract as the engineering board).

import type { Ticket } from "./types";

export const SEED_MARKETING: Ticket[] = [
  {
    id: "xls-1",
    title: "Fix incoming VentureCite email",
    detail:
      "Configure info@venturecite.com so the team can receive incoming messages without delivery errors.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 1.0",
    column: "doing",
    order: 1,
    brand: "VentureCite",
    assignee: "Ben",
    status: "I updated it and sent screenshot with question re DKIM",
    link: "",
    notes: "",
  },
  {
    id: "xls-2",
    title: "Create VentureCite LinkedIn page",
    detail: "Create the company LinkedIn page and grant Vandan and LitLabs administrator access.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 2.0",
    column: "doing",
    order: 2,
    brand: "VentureCite",
    assignee: "Ben",
    status: "Complete - needs admin contacts added, content/logo etc.",
    link: "",
    notes: "",
  },
  {
    id: "xls-6",
    title: "Publish social warm-up posts",
    detail:
      "Begin publishing the prepared static creatives across Facebook, Instagram, YouTube, and LinkedIn.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 6.0",
    column: "next",
    order: 6,
    brand: "VentureCite",
    assignee: "LitLabs",
    status: "Ready to Start",
    link: "",
    notes: "",
  },
  {
    id: "xls-11",
    title: "Share VentureCite Calendly embed",
    detail: "Provide the inline embed code for the VentureCite consultation booking page.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 11.0",
    column: "backlog",
    order: 11,
    brand: "VentureCite",
    assignee: "Ben",
    status: "To Do",
    link: "",
    notes: "",
  },
  {
    id: "xls-12",
    title: "Configure VentureCite Calendly meeting",
    detail: "Set the schedule to Spain time and use Google Meet as the meeting location.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 12.0",
    column: "backlog",
    order: 12,
    brand: "VentureCite",
    assignee: "Ben",
    status: "To Do",
    link: "",
    notes: "",
  },
  {
    id: "xls-23",
    title: "Respond to the recent Venture PR lead",
    detail: "Review the recent lead thread and send the appropriate response.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 1.0",
    column: "backlog",
    order: 23,
    brand: "VenturePR",
    assignee: "Ben",
    status: "To Do",
    link: "",
    notes: "The main email was copied on the existing thread.",
  },
  {
    id: "xls-24",
    title: "Check LinkedIn follow-ups from interns",
    detail: "Confirm whether the interns followed up with every assigned lead through LinkedIn.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 2.0",
    column: "backlog",
    order: 24,
    brand: "VenturePR",
    assignee: "Vandan / LitLabs",
    status: "To Do",
    link: "https://docs.google.com/spreadsheets/d/1E_XTpqcIhkfxWQV5g9AxfFmlql0WODGFFR40L3DFmOQ/edit",
    notes: "Check with Ben and the interns.",
  },
  {
    id: "xls-25",
    title: "Continue lead follow-ups by email",
    detail: "After LinkedIn outreach, follow up with interested or unresponsive leads by email.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 3.0",
    column: "blocked",
    order: 25,
    brand: "VenturePR",
    assignee: "Paid Interns",
    status: "Blocked",
    link: "https://docs.google.com/spreadsheets/d/1E_XTpqcIhkfxWQV5g9AxfFmlql0WODGFFR40L3DFmOQ/edit",
    notes: "Start after LinkedIn follow-ups are completed.",
  },
  {
    id: "xls-26",
    title: "Prepare outreach scripts for interns",
    detail: "Provide concise LinkedIn and email scripts for initial contact and follow-up.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 4.0",
    column: "backlog",
    order: 26,
    brand: "VenturePR",
    assignee: "Vandan / LitLabs",
    status: "To Do",
    link: "",
    notes: "",
  },
  {
    id: "xls-36",
    title: "Diagnose the email campaign performance",
    detail:
      "Review why the new campaign was not launched and why the current approach is not generating results.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 14.0",
    column: "doing",
    order: 36,
    brand: "VenturePR",
    assignee: "Vandan / LitLabs",
    status: "In Progress",
    link: "",
    notes:
      "Did not perform the new campaign, we are looking into creating a strategy around how we can approach new leads. Why is it not working now.",
  },
  {
    id: "xls-37",
    title: "Create a new email campaign strategy",
    detail:
      "Build a revised approach for new leads, including targeting, positioning, messaging, and sequence.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 15.0",
    column: "doing",
    order: 37,
    brand: "VenturePR",
    assignee: "Vandan / LitLabs",
    status: "In Progress",
    link: "",
    notes: "Document the strategy before launching.",
  },
  {
    id: "xls-38",
    title: "Review the email strategy and copy",
    detail: "Review the proposed campaign strategy and approve the outreach copy.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 16.0",
    column: "blocked",
    order: 38,
    brand: "VenturePR",
    assignee: "Ben",
    status: "Blocked",
    link: "",
    notes: "Waiting for the revised strategy and copy.",
  },
  {
    id: "xls-39",
    title: "Launch the next email campaign",
    detail: "Launch the approved campaign using the new strategy and target list.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 17.0",
    column: "blocked",
    order: 39,
    brand: "VenturePR",
    assignee: "Vandan",
    status: "Blocked",
    link: "",
    notes: "Launch after Ben approves the strategy and copy.",
  },
  {
    id: "xls-40",
    title: "Monitor email campaign results",
    detail:
      "Track replies, positive leads, booked calls, objections, and deliverability after launch.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 18.0",
    column: "blocked",
    order: 40,
    brand: "VenturePR",
    assignee: "Vandan / LitLabs",
    status: "Blocked",
    link: "",
    notes: "Use the findings to improve the campaign.",
  },
  {
    id: "xls-43",
    title: "VentureFlex Meta Ads Strategy",
    detail: "Finalize the Meta ads targeting, messaging, campaign structure, and budget plan.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · Venture Flex · Task 2.0",
    column: "done",
    order: 43,
    brand: "VentureFlex",
    assignee: "LitLabs",
    status: "Done",
    link: "https://docs.google.com/document/d/1FKnfHF1qHOdndy9jKf3BPBebz7ervpTuU2vcED7WtAc/edit?tab=t.0#heading=h.ty21o54b2rin",
    notes: "Use the approved strategy for campaign setup.",
  },
  {
    id: "xls-45",
    title: "Launch VentureFlex",
    detail:
      "Complete the launch setup and publish VentureFlex across the approved website and marketing channels.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · Venture Flex · Task 4.0",
    column: "blocked",
    order: 45,
    brand: "VentureFlex",
    assignee: "LitLabs",
    status: "Blocked",
    link: "https://ventureflex.vercel.app/",
    notes: "Launch after the website, socials, ads, and marketing video are ready.",
  },
  {
    id: "xls-46",
    title: "Create VentureFlex Social Pages",
    detail: "Create VentureFlex LinkedIn, Instagram, and Facebook pages and provide admin access.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · Venture Flex · Task 5.0",
    column: "backlog",
    order: 46,
    brand: "VentureFlex",
    assignee: "Ben",
    status: "To Do",
    link: "",
    notes: "",
  },
];

export const SEED_CONTENT: Ticket[] = [
  {
    id: "xls-3",
    title: "Send VentureCite video examples",
    detail:
      "Share examples covering clothing, background, framing, delivery style, and final edit format.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 3.0",
    column: "done",
    order: 3,
    brand: "VentureCite",
    assignee: "Vandan / LitLabs",
    status: "Done",
    link: "",
    notes: "",
  },
  {
    id: "xls-4",
    title: "Launch Video",
    detail: "Ben to record the VentureCite launch video.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 4.0",
    column: "backlog",
    order: 4,
    brand: "VentureCite",
    assignee: "Ben",
    status: "To Do",
    link: "",
    notes: "",
  },
  {
    id: "xls-5",
    title: "Edit VentureCite launch video",
    detail: "Edit Ben's recording into the final launch video and prepare social versions.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 5.0",
    column: "blocked",
    order: 5,
    brand: "VentureCite",
    assignee: "LitLabs",
    status: "Blocked",
    link: "",
    notes: "",
  },
  {
    id: "xls-19",
    title: "Prepare the launch content schedule",
    detail: "Coordinate launch videos, static posts, product demos, and outreach activity.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 19.0",
    column: "backlog",
    order: 19,
    brand: "VentureCite",
    assignee: "Vandan / LitLabs",
    status: "To Do",
    link: "",
    notes: "",
  },
  {
    id: "xls-21",
    title: "Marketing Video Reshoot",
    detail:
      "Ben to reshoot the marketing video using the supplied Facebook ad examples as references.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 21.0",
    column: "backlog",
    order: 21,
    brand: "VentureCite",
    assignee: "Ben",
    status: "To Do",
    link: "https://www.facebook.com/ads/library/?id=876474384714420\nhttps://www.facebook.com/ads/library/?id=1589686552155595",
    notes: "Match the pacing, presentation style, and structure of the reference ads.",
  },
  {
    id: "xls-28",
    title: "Create thumbnails for the articles",
    detail: "Design a matching thumbnail or cover image for each approved article.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 6.0",
    column: "doing",
    order: 28,
    brand: "VenturePR",
    assignee: "LitLabs",
    status: "In Progress",
    link: "",
    notes: "Starts after the article topics and titles are confirmed.",
  },
  {
    id: "xls-33",
    title: "Review Venture PR content calendar",
    detail: "Review the social calendar and approve the upcoming posts.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 11.0",
    column: "backlog",
    order: 33,
    brand: "VenturePR",
    assignee: "Ben",
    status: "To Do",
    link: "https://docs.google.com/spreadsheets/d/19mnaZygTv_oO1NCmM53smEC3DJkr_PAM-LGvo2kfUng/edit?gid=0#gid=0",
    notes: "Confirm topics, results, and posting schedule.",
  },
  {
    id: "xls-34",
    title: "Collect recent case-study briefs",
    detail:
      "Ask the Venture PR team for recent client problems, solutions, results, and testimonials.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 12.0",
    column: "backlog",
    order: 34,
    brand: "VenturePR",
    assignee: "Ben",
    status: "To Do",
    link: "",
    notes: "Use a consistent case-study template.",
  },
  {
    id: "xls-35",
    title: "Create case-study content",
    detail: "Turn approved briefs into website case studies and reusable social content.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 13.0",
    column: "backlog",
    order: 35,
    brand: "VenturePR",
    assignee: "Vandan / LitLabs",
    status: "To Do",
    link: "",
    notes: "Waiting for case-study information from Ben's team.",
  },
  {
    id: "xls-44",
    title: "VentureFlex Ads Creatives",
    detail: "Complete the VentureFlex ad creatives based on the approved Meta ads strategy.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · Venture Flex · Task 3.0",
    column: "next",
    order: 44,
    brand: "VentureFlex",
    assignee: "LitLabs",
    status: "Ready to review",
    link: "https://www.figma.com/design/GcMTs96ACUUJUR5V9QLGTE/VenturePR_-Content?node-id=0-1&p=f&t=Y7pxPBMCiSGdqfu0-0",
    notes: "Prepare final sizes and copy variations for launch.",
  },
  {
    id: "xls-47",
    title: "Record VentureFlex Marketing Video",
    detail: "Record the VentureFlex marketing video using the approved UGC scripts.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · Venture Flex · Task 6.0",
    column: "backlog",
    order: 47,
    brand: "VentureFlex",
    assignee: "Ben",
    status: "To Do",
    link: "https://docs.google.com/document/d/1ad3yclS_s66yhidQ4hH3K60tQKojJ_7Mvbi2am7qBMY/edit?usp=drivesdk",
    notes: "Send the recording to LitLabs for editing.",
  },
];

export const SEED_AEO: Ticket[] = [
  {
    id: "xls-14",
    title: "Launch PR plus GEO outreach",
    detail: "Launch the combined PR and GEO campaign and send Ben the final copy for review.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 14.0",
    column: "doing",
    order: 14,
    brand: "VentureCite",
    assignee: "Vandan",
    status: "In Progress",
    link: "",
    notes: "",
  },
  {
    id: "xls-15",
    title: "Validate AI citation tracking",
    detail:
      "Confirm citation checks work correctly across xAI, ChatGPT, Gemini, and other supported models.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 15.0",
    column: "doing",
    order: 15,
    brand: "VentureCite",
    assignee: "LitLabs",
    status: "In Progress",
    link: "",
    notes: "",
  },
  {
    id: "xls-41",
    title: "Launch PR plus GEO outreach",
    detail:
      "Launch the combined PR and GEO outreach campaign and send Ben the final copy for review.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 19.0",
    column: "doing",
    order: 41,
    brand: "VenturePR",
    assignee: "Vandan",
    status: "In Progress",
    link: "",
    notes: "Test interest in both PR and GEO services.",
  },
];

export const SEED_BEN: Ticket[] = [
  {
    id: "xls-27",
    title: "Draft articles for Ben to post",
    detail: "Write thought-leadership articles for Ben's LinkedIn and other suitable channels.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 5.0",
    column: "next",
    order: 27,
    brand: "VenturePR",
    assignee: "LitLabs",
    status: "Ready to Post",
    link: "https://docs.google.com/document/d/1W1hjI2Xxa4CS3dyeCTuHWA8W8pKQYzxhAKooCa6BVWM/edit?tab=t.bzmg5k3x10pk",
    notes: "Add each draft link here when ready.",
  },
  {
    id: "xls-29",
    title: "Prepare Ben's personal content plan",
    detail: "Build the next batch of personal-brand topics, scripts, and posting dates.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 7.0",
    column: "doing",
    order: 29,
    brand: "VenturePR",
    assignee: "LitLabs",
    status: "In Progress",
    link: "",
    notes: "Focus on content that supports Venture PR authority.",
  },
  {
    id: "xls-30",
    title: "Review Ben's next script batch",
    detail: "Review the next batch of personal-brand scripts shared by Rehman.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 8.0",
    column: "next",
    order: 30,
    brand: "VenturePR",
    assignee: "Ben",
    status: "Ben to Record",
    link: "https://docs.google.com/document/d/1tDE4uZIDUrRDZuK2moWM_7Hidp8M75ur6XxOy9ZNxPs/edit?usp=sharing",
    notes: "Provide comments before production begins.",
  },
  {
    id: "xls-31",
    title: "Edit and colour-grade Ben's reels",
    detail: "Apply the requested edits and make Ben's skin tone look more natural.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 9.0",
    column: "done",
    order: 31,
    brand: "VenturePR",
    assignee: "LitLabs",
    status: "Done/Approved",
    link: "https://drive.google.com/drive/folders/1D0nJKZBPvBrdiSglvkub_Zr41vFfeBj5",
    notes: "Send updated reels to Ben for approval.",
  },
  {
    id: "xls-32",
    title: "Publish approved personal content",
    detail: "Schedule and publish Ben's approved reels and personal-brand posts.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VenturePR · Task 10.0",
    column: "next",
    order: 32,
    brand: "VenturePR",
    assignee: "LitLabs",
    status: "Scheduled",
    link: "https://drive.google.com/drive/folders/1D0nJKZBPvBrdiSglvkub_Zr41vFfeBj6",
    notes: "Only publish after Ben's approval.",
  },
];

/** Spreadsheet rows that are engineering work. Appended to the existing
 *  codebase-audit seed rather than replacing it. */
export const SEED_ENGINEERING_IMPORTED: Ticket[] = [
  {
    id: "xls-7",
    title: "Send Stripe test instructions",
    detail: "Send the test link, steps, dummy card details, and expected checkout result.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 7.0",
    column: "backlog",
    order: 7,
    brand: "VentureCite",
    assignee: "Vandan / LitLabs",
    status: "To Do",
    link: "",
    notes: "",
  },
  {
    id: "xls-8",
    title: "Test Stripe checkout",
    detail: "Complete a dummy purchase for each plan and report any payment or access issues.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 8.0",
    column: "blocked",
    order: 8,
    brand: "VentureCite",
    assignee: "Ben",
    status: "Blocked",
    link: "",
    notes: "",
  },
  {
    id: "xls-9",
    title: "Push Stripe payments to production",
    detail: "Move the approved checkout from test mode to production after Ben signs off.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 9.0",
    column: "blocked",
    order: 9,
    brand: "VentureCite",
    assignee: "LitLabs",
    status: "Blocked",
    link: "",
    notes: "",
  },
  {
    id: "xls-10",
    title: "Verify pricing and plan access",
    detail:
      "Confirm the $99 and $500 plans, trial terms, and unlocked features match the approved offer.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 10.0",
    column: "doing",
    order: 10,
    brand: "VentureCite",
    assignee: "LitLabs",
    status: "In Review",
    link: "",
    notes: "",
  },
  {
    id: "xls-13",
    title: "Add Calendly to the enterprise page",
    detail: "Embed the approved meeting option and test the full booking flow.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 13.0",
    column: "blocked",
    order: 13,
    brand: "VentureCite",
    assignee: "Vandan / LitLabs",
    status: "Blocked",
    link: "",
    notes: "",
  },
  {
    id: "xls-16",
    title: "Collect product feedback",
    detail:
      "Ask the team to test VentureCite and log bugs, usability issues, and improvement ideas.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 16.0",
    column: "doing",
    order: 16,
    brand: "VentureCite",
    assignee: "Vandan / LitLabs",
    status: "In Progress",
    link: "",
    notes: "",
  },
  {
    id: "xls-17",
    title: "Verify onboarding buttons",
    detail: "Retest the onboarding flow and confirm every button leads to the correct next step.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 17.0",
    column: "doing",
    order: 17,
    brand: "VentureCite",
    assignee: "LitLabs",
    status: "In Review",
    link: "",
    notes: "",
  },
  {
    id: "xls-18",
    title: "Run VentureCite launch QA",
    detail:
      "Test email delivery, signup, onboarding, payments, booking, mobile layout, and core product flows.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 18.0",
    column: "blocked",
    order: 18,
    brand: "VentureCite",
    assignee: "LitLabs",
    status: "Blocked",
    link: "",
    notes: "",
  },
  {
    id: "xls-20",
    title: "Approve public launch readiness",
    detail: "Confirm the product, payments, booking, email, and content are ready for promotion.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 20.0",
    column: "blocked",
    order: 20,
    brand: "VentureCite",
    assignee: "Ben",
    status: "Blocked",
    link: "",
    notes: "",
  },
  {
    id: "xls-22",
    title: "Engineering Update",
    detail:
      "Provide a complete update on all engineering work, progress, blockers, and next steps.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · VentureCite · Task 22.0",
    column: "backlog",
    order: 22,
    brand: "VentureCite",
    assignee: "LitLabs",
    status: "To Do",
    link: "",
    notes: "",
  },
  {
    id: "xls-42",
    title: "VentureFlex Website",
    detail: "Review and complete the VentureFlex website for launch.",
    kind: "task",
    weight: "medium",
    area: "",
    evidence: "Venture Task Tracker.xlsx · Venture Flex · Task 1.0",
    column: "doing",
    order: 42,
    brand: "VentureFlex",
    assignee: "LitLabs",
    status: "In Progress/Waiting on Ben Feedback",
    link: "https://ventureflex.vercel.app/",
    notes: "Verify pages, forms, mobile layout, and launch readiness.",
  },
];
