import type { Board12Data, Board12EvidenceGap, Board12SourceSignal, Board12Value } from "./Screen";

const measured = <T>(value: T): Board12Value<T> => ({ kind: "measured", value });

const sourceRows: readonly Board12SourceSignal[] = [
  {
    id: "first-party",
    sourceType: measured("First-party website"),
    description: measured("Your site, pages, and content"),
    icon: "globe",
    detected: measured(248),
    verified: measured(186),
    status: measured("detected"),
    trend: measured({ delta: 12, points: [19, 17, 18, 13, 15, 10, 11, 6, 5] }),
  },
  {
    id: "structured-entities",
    sourceType: measured("Structured entities"),
    description: measured("Knowledge graphs and schemas"),
    icon: "doc",
    detected: measured(52),
    verified: measured(28),
    status: measured("confirmation"),
    trend: measured({ delta: 5, points: [18, 16, 17, 12, 13, 9, 10, 7, 7] }),
  },
  {
    id: "third-party-mentions",
    sourceType: measured("Trusted third-party mentions"),
    description: measured("Authoritative sites and media"),
    icon: "link",
    detected: measured(120),
    verified: measured(61),
    status: measured("verified"),
    trend: measured({ delta: 18, points: [20, 18, 19, 14, 12, 13, 9, 6, 4] }),
  },
  {
    id: "review-sources",
    sourceType: measured("Review sources"),
    description: measured("G2, Capterra, Trustpilot, etc."),
    icon: "star",
    detected: measured(36),
    verified: measured(14),
    status: measured("stale"),
    trend: measured({ delta: -6, points: [6, 8, 7, 11, 12, 15, 14, 18, 19] }),
  },
  {
    id: "community-discussions",
    sourceType: measured("Community discussions"),
    description: measured("Reddit, LinkedIn, forums"),
    icon: "mail",
    detected: measured(84),
    verified: measured(37),
    status: measured("detected"),
    trend: measured({ delta: 22, points: [20, 19, 15, 16, 11, 12, 8, 5, 4] }),
  },
  {
    id: "fresh-evidence",
    sourceType: measured("Fresh evidence"),
    description: measured("Recent, dated, and reproducible content"),
    icon: "doc",
    detected: measured(70),
    verified: measured(21),
    status: measured("confirmation"),
    trend: measured({ delta: 9, points: [19, 17, 18, 14, 15, 11, 9, 8, 7] }),
  },
];

const missingEvidence: readonly Board12EvidenceGap[] = [
  {
    id: "founder-credentials",
    title: "Founder credentials on trusted profiles",
    detail: "LinkedIn, Crunchbase, industry bios",
  },
  {
    id: "customer-logos",
    title: "Recent customer logos with context",
    detail: "Add logos and short case descriptions",
  },
  {
    id: "expert-quotes",
    title: "Third-party expert quotes",
    detail: "Independent validation from industry voices",
  },
  {
    id: "press-mentions",
    title: "Updated press mentions (last 90 days)",
    detail: "Earned media and analyst coverage",
  },
];

export const board12Fixture: Board12Data = {
  brandId: "fixture-brand",
  brand: { name: measured("VenturePR") },
  signalCoverage: {
    score: measured(64),
    previousScore: measured(58),
    change: measured(6),
    periodStart: "Aug 10",
    periodEnd: "Sep 9",
    series: measured({
      primary: [
        { x: "Aug 10", y: 33 },
        { x: "", y: 37 },
        { x: "", y: 40 },
        { x: "", y: 38 },
        { x: "", y: 37 },
        { x: "", y: 39 },
        { x: "", y: 44 },
        { x: "Aug 17", y: 50 },
        { x: "", y: 48 },
        { x: "", y: 52 },
        { x: "", y: 55 },
        { x: "Aug 24", y: 52 },
        { x: "", y: 57 },
        { x: "", y: 60 },
        { x: "", y: 58 },
        { x: "Aug 31", y: 61 },
        { x: "", y: 63 },
        { x: "", y: 60 },
        { x: "", y: 62 },
        { x: "Sep 9", y: 64 },
      ],
      median: [
        { x: "Aug 10", y: 20 },
        { x: "", y: 24 },
        { x: "", y: 27 },
        { x: "", y: 30 },
        { x: "", y: 28 },
        { x: "", y: 26 },
        { x: "", y: 32 },
        { x: "Aug 17", y: 34 },
        { x: "", y: 33 },
        { x: "", y: 36 },
        { x: "", y: 38 },
        { x: "Aug 24", y: 36 },
        { x: "", y: 34 },
        { x: "", y: 38 },
        { x: "", y: 42 },
        { x: "Aug 31", y: 40 },
        { x: "", y: 44 },
        { x: "", y: 43 },
        { x: "", y: 46 },
        { x: "Sep 9", y: 50 },
      ],
      xLabels: ["Aug 10", "Aug 17", "Aug 24", "Aug 31", "Sep 9"],
    }),
  },
  sourceSignals: sourceRows,
  sourceMix: {
    verifiedTotal: measured(186),
    segments: [
      { id: "first-party", label: measured("First-party website"), share: measured(36) },
      { id: "third-party", label: measured("Third-party mentions"), share: measured(24) },
      { id: "community", label: measured("Community discussions"), share: measured(15) },
      { id: "entities", label: measured("Structured entities"), share: measured(12) },
      { id: "reviews", label: measured("Review sources"), share: measured(8) },
      { id: "fresh", label: measured("Fresh evidence"), share: measured(5) },
    ],
  },
  opportunity: {
    title: measured("Strengthen founder credentials on trusted profiles"),
    description: measured(
      "Make founder expertise easier for AI systems to verify through authoritative profiles.",
    ),
    points: measured(40),
    evidence: measured(
      "Founder bio is incomplete on LinkedIn and Crunchbase; missing recent role and key accomplishments.",
    ),
    mechanism: measured(
      "Stronger, consistent founder signals can improve entity resolution and trust across engines.",
    ),
    uncertainty: measured("Medium"),
    uncertaintyDetail: measured("Likely to help, but impact may vary by engine."),
  },
  missingEvidence,
  nextVerification: {
    title: measured("Verify Crunchbase founder profile"),
    detail: measured("Confirm current role, bio, and recent activity."),
    why: measured("Helps AI engines link founder expertise to VenturePR across sources."),
    effort: measured(10),
    upside: measured("Medium"),
  },
};
