// Integration test: exercises admitSession and deleteExpiredUnclaimedSessions
// against a real Postgres.
//
// WHY THIS FILE EXISTS. tests/unit/onboardingSessionStore.test.ts mocks
// `pool` entirely, so it proves the query shape and the branching (created /
// rate_limited / live_session_exists) but never sends real SQL: the
// pg_advisory_xact_lock serialization under concurrency, and the partial
// index the cleanup sweep relies on, are only proven by a real database.
//
// HOW TO RUN
//   npx supabase start
//   TEST_DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:55322/postgres \
//   LOCAL_SUPABASE_TEST=1 npx vitest run tests/integration/onboardingAdmission.test.ts
//
// Without TEST_DATABASE_URL the file skips, so CI and ordinary `npm test`
// runs are unaffected. Per CLAUDE.md standing rules, this file is written
// but deliberately NOT run here - the owner runs the database suite
// separately.
//
// ISOLATION CONTRACT. Every row this file creates carries a fixture ip_hash
// or session id generated by this file. Assertions scope to those, and
// cleanup deletes only those rows, so the file is safe to run against a
// database that holds other data.
import { afterEach, describe, expect, it } from "vitest";
import { randomUUID } from "node:crypto";
import { sql } from "drizzle-orm";
import { configureDestructiveDatabaseTest } from "../helpers/destructiveDatabaseTest";

const databaseTest = configureDestructiveDatabaseTest(process.env);

if (databaseTest.kind === "ready") {
  const { db, pool } = await import("../../server/db");
  const { admitSession, deleteExpiredUnclaimedSessions } =
    await import("../../server/onboardingSession/store");

  const FIXTURE_TAG = "f-onboarding-admission";

  function fixtureIpHash(): string {
    return `${FIXTURE_TAG}-${randomUUID()}`;
  }

  async function removeSessionsForIp(ipHash: string) {
    await db.execute(sql`DELETE FROM onboarding_sessions WHERE ip_hash = ${ipHash}`);
  }

  async function insertRawSession(overrides: {
    id?: string;
    ipHash: string;
    domain?: string;
    status?: string;
    claimedBy?: string | null;
    expiresAt: Date;
  }): Promise<string> {
    const id = overrides.id ?? randomUUID();
    await db.execute(sql`
      INSERT INTO onboarding_sessions (id, domain, ip_hash, status, claimed_by, claimed_at, expires_at)
      VALUES (
        ${id},
        ${overrides.domain ?? "fixture.example"},
        ${overrides.ipHash},
        ${overrides.status ?? "running"},
        ${overrides.claimedBy ?? null},
        ${overrides.claimedBy ? sql`now()` : null},
        ${overrides.expiresAt.toISOString()}
      )
    `);
    return id;
  }

  describe("admitSession (integration)", () => {
    it("lets 8 concurrent admits from one IP produce at most 5 created sessions", async () => {
      const ipHash = fixtureIpHash();
      try {
        const results = await Promise.all(
          Array.from({ length: 8 }, () => admitSession({ domain: "fixture.example", ipHash })),
        );

        const created = results.filter((r) => r.kind === "created");
        const rateLimited = results.filter((r) => r.kind === "rate_limited");
        const live = results.filter((r) => r.kind === "live_session_exists");

        // At most one "created" can exist as the first live session; every
        // subsequent admit from the same still-running IP sees it as
        // live_session_exists rather than counting toward the hourly cap.
        // Either way, the hourly cap of 5 must never be exceeded, and no
        // more than one session should ever be inserted for a single IP
        // while one is still live.
        expect(created.length).toBeGreaterThan(0);
        expect(created.length).toBeLessThanOrEqual(5);
        expect(created.length + rateLimited.length + live.length).toBe(8);

        const rows = await db.execute(
          sql`SELECT count(*)::int AS count FROM onboarding_sessions WHERE ip_hash = ${ipHash}`,
        );
        const rowCount = Number(
          (rows as unknown as { rows: Array<{ count: number }> }).rows[0]?.count ?? 0,
        );
        expect(rowCount).toBeLessThanOrEqual(5);
      } finally {
        await removeSessionsForIp(ipHash);
      }
    });

    it("serializes concurrent admits across the hourly cap without a race window", async () => {
      const ipHash = fixtureIpHash();
      try {
        // Pre-fill 4 sessions in the past hour (not live: status done), so one
        // more slot remains under the cap of 5.
        for (let i = 0; i < 4; i += 1) {
          await insertRawSession({
            ipHash,
            status: "done",
            expiresAt: new Date(Date.now() + 60_000),
          });
        }

        const results = await Promise.all(
          Array.from({ length: 8 }, () => admitSession({ domain: "fixture.example", ipHash })),
        );
        const created = results.filter((r) => r.kind === "created");
        const liveExists = results.filter((r) => r.kind === "live_session_exists");

        // Exactly one more session is created: the advisory lock serializes
        // the 8 admits, so none can slip past a stale count. The other 7 see
        // the session the first one created (status running) and get
        // live_session_exists, which admitSession checks before the hourly
        // cap - a double-click resumes the running session rather than 429.
        expect(created.length).toBe(1);
        expect(liveExists.length).toBe(7);
        expect(new Set(liveExists.map((r) => (r as { sessionId: string }).sessionId))).toEqual(
          new Set([(created[0] as { session: { id: string } }).session.id]),
        );
      } finally {
        await removeSessionsForIp(ipHash);
      }
    });
  });

  describe("deleteExpiredUnclaimedSessions (integration)", () => {
    it("removes an expired unclaimed row but keeps an expired claimed row", async () => {
      const ipHash = fixtureIpHash();
      const userId = `${FIXTURE_TAG}-user-${randomUUID()}`;
      await db.execute(sql`
        INSERT INTO users (id, email, access_tier)
        VALUES (${userId}, ${`${userId}@example.com`}, 'free')
      `);

      const expiredUnclaimedId = await insertRawSession({
        ipHash,
        status: "done",
        claimedBy: null,
        expiresAt: new Date(Date.now() - 60_000),
      });
      const expiredClaimedId = await insertRawSession({
        ipHash,
        status: "done",
        claimedBy: userId,
        expiresAt: new Date(Date.now() - 60_000),
      });

      try {
        await deleteExpiredUnclaimedSessions();

        const remaining = await db.execute(
          sql`SELECT id FROM onboarding_sessions WHERE ip_hash = ${ipHash}`,
        );
        const remainingIds = (remaining as unknown as { rows: Array<{ id: string }> }).rows.map(
          (r) => r.id,
        );
        expect(remainingIds).not.toContain(expiredUnclaimedId);
        expect(remainingIds).toContain(expiredClaimedId);
      } finally {
        await removeSessionsForIp(ipHash);
        await db.execute(sql`DELETE FROM users WHERE id = ${userId}`);
      }
    });
  });

  afterEach(async () => {
    // Belt-and-suspenders in case an assertion threw before a test's own
    // cleanup ran.
    await pool.query("DELETE FROM onboarding_sessions WHERE ip_hash LIKE $1", [`${FIXTURE_TAG}-%`]);
  });
} else {
  describe.skip("admitSession / deleteExpiredUnclaimedSessions (integration) - skipped, no TEST_DATABASE_URL", () => {
    it("skipped", () => {});
  });
}
