import type { Board13Data, Board13Value } from "./Screen";

const measured = <T>(value: T): Board13Value<T> => ({ kind: "measured", value });

export const board13Fixture = {
  brandId: measured("brand-venture-pr"),
  brandName: measured("VenturePR"),
  summary: measured(
    "AI answers generally describe VenturePR accurately, but key themes are missing or unclear. The most significant gap is startup specialization, which is mentioned inconsistently. A few answers contain partial or conflicting claims, and some impressions cannot be verified from our sources.",
  ),
  accurateThemes: measured(3),
  missingThemes: measured(2),
  conflictingClaims: measured(1),
  unverifiedImpressions: measured(2),
  themes: measured([
    {
      id: "public-relations-for-growing-businesses",
      name: measured("Public relations for growing businesses"),
      observed: measured("Described as a PR agency helping growing companies and startups."),
      approved: measured("Public relations services for growing businesses."),
      coverage: measured("High"),
      coverageCount: measured(3),
      coverageTotal: measured(4),
      coverageRate: measured(0.75),
      confidence: measured("High"),
      action: measured("Keep"),
      selected: false,
    },
    {
      id: "startup-specialization",
      name: measured("Startup specialization"),
      observed: measured(
        "Startup specialization is unclear. Some answers mention startups, others describe a general PR agency.",
      ),
      approved: measured("Focus on startups and high-growth companies."),
      coverage: measured("Low"),
      coverageCount: measured(1),
      coverageTotal: measured(4),
      coverageRate: measured(0.25),
      confidence: measured("Medium"),
      action: measured("Prioritize"),
      selected: true,
    },
    {
      id: "services-offered",
      name: measured("Services offered"),
      observed: measured("Lists media relations, content, and thought leadership."),
      approved: measured("Media relations, content, thought leadership, and GEO optimization."),
      coverage: measured("Medium"),
      coverageCount: measured(2),
      coverageTotal: measured(4),
      coverageRate: measured(0.5),
      confidence: measured("High"),
      action: measured("Keep"),
      selected: false,
    },
    {
      id: "geographic-focus",
      name: measured("Geographic focus"),
      observed: measured("Often described as India-focused."),
      approved: measured("Primarily serves startups in India."),
      coverage: measured("High"),
      coverageCount: measured(3),
      coverageTotal: measured(4),
      coverageRate: measured(0.75),
      confidence: measured("High"),
      action: measured("Keep"),
      selected: false,
    },
    {
      id: "ai-geo-expertise",
      name: measured("AI / GEO expertise"),
      observed: measured("Occasionally mentioned; not consistent."),
      approved: measured("GEO optimization for AI search visibility."),
      coverage: measured("Low"),
      coverageCount: measured(1),
      coverageTotal: measured(4),
      coverageRate: measured(0.25),
      confidence: measured("Medium"),
      action: measured("Improve"),
      selected: false,
    },
    {
      id: "enterprise-clients",
      name: measured("Enterprise clients (large brands)"),
      observed: measured("One answer suggests work with large enterprises."),
      approved: measured("Focus on startups and growing businesses (not large enterprises)."),
      coverage: measured("Conflicting"),
      coverageCount: measured(1),
      coverageTotal: measured(4),
      coverageRate: measured(0.25),
      confidence: measured("Low"),
      action: measured("Clarify"),
      selected: false,
    },
  ]),
  answers: measured([
    {
      id: "chatgpt",
      model: measured("ChatGPT"),
      snippet: measured(
        "VenturePR is a PR agency that helps startups and growing companies with media relations and content.",
      ),
      sourceUrl: measured("https://chat.openai.com/…"),
      sourceHref: measured("https://chat.openai.com/"),
      retrievedAt: measured("9 Sep 2026"),
    },
    {
      id: "gemini",
      model: measured("Gemini"),
      snippet: measured(
        "VenturePR is a communications firm based in India that works with startups. Specific startup focus is not clearly mentioned.",
      ),
      sourceUrl: measured("https://gemini.google.com/…"),
      sourceHref: measured("https://gemini.google.com/"),
      retrievedAt: measured("9 Sep 2026"),
    },
    {
      id: "claude",
      model: measured("Claude"),
      snippet: measured(
        "VenturePR helps businesses with PR and thought leadership. It may work with companies of various sizes.",
      ),
      sourceUrl: measured("https://claude.ai/…"),
      sourceHref: measured("https://claude.ai/"),
      retrievedAt: measured("9 Sep 2026"),
    },
    {
      id: "perplexity",
      model: measured("Perplexity"),
      snippet: measured(
        "VenturePR is described as a PR agency for growing businesses in India, with services including media relations.",
      ),
      sourceUrl: measured("https://www.perplexity.ai/…"),
      sourceHref: measured("https://www.perplexity.ai/"),
      retrievedAt: measured("9 Sep 2026"),
    },
  ]),
  successfulAnswers: measured(4),
  mentionedAnswers: measured(3),
  measuredAt: measured("9 Sep 2026"),
  evidenceBoundaries: {
    observed: measured("Brand mentioned in 3 of 4 successful answers"),
    unknown: measured("Why each model omitted or varied the brand"),
    nextCheck: measured("Repeat the same question set after the next content change"),
    noCausalClaim: measured(
      "This task shows how AI answers describe your brand. It does not prove why these patterns occur.",
    ),
    finalNote: measured("We avoid blame and focus on useful experiments."),
  },
} satisfies Board13Data;
