// Single source of truth for the industry list. Imported by the Content page,
// brand setup, and keyword research so we never drift between three copies.
//
// Each entry has a `value` (canonical, used for storage + prompt
// interpolation) and a `group` (used for the optgroup in the combobox).

export type Industry = { value: string; group: string };

export const INDUSTRIES: Industry[] = [
  { value: "Technology", group: "Technology & Digital" },
  { value: "Software & SaaS", group: "Technology & Digital" },
  { value: "Artificial Intelligence & Machine Learning", group: "Technology & Digital" },
  { value: "Cybersecurity", group: "Technology & Digital" },
  { value: "Telecommunications", group: "Technology & Digital" },
  { value: "E-commerce", group: "Technology & Digital" },
  { value: "Gaming & Esports", group: "Technology & Digital" },
  { value: "Healthcare", group: "Healthcare & Life Sciences" },
  { value: "Pharmaceuticals", group: "Healthcare & Life Sciences" },
  { value: "Biotechnology", group: "Healthcare & Life Sciences" },
  { value: "Medical Devices", group: "Healthcare & Life Sciences" },
  { value: "Mental Health & Wellness", group: "Healthcare & Life Sciences" },
  { value: "Finance & Banking", group: "Finance & Business" },
  { value: "Insurance", group: "Finance & Business" },
  { value: "Fintech", group: "Finance & Business" },
  { value: "Accounting & Tax", group: "Finance & Business" },
  { value: "Real Estate", group: "Finance & Business" },
  { value: "Venture Capital & Private Equity", group: "Finance & Business" },
  { value: "Consulting & Professional Services", group: "Finance & Business" },
  { value: "Legal Services", group: "Finance & Business" },
  { value: "Marketing & Advertising", group: "Marketing & Media" },
  { value: "Public Relations", group: "Marketing & Media" },
  { value: "Media & Entertainment", group: "Marketing & Media" },
  { value: "Publishing", group: "Marketing & Media" },
  { value: "Social Media & Influencer", group: "Marketing & Media" },
  { value: "Education & EdTech", group: "Education & Nonprofit" },
  { value: "Higher Education", group: "Education & Nonprofit" },
  { value: "Nonprofit & NGO", group: "Education & Nonprofit" },
  { value: "Government & Public Sector", group: "Education & Nonprofit" },
  { value: "Manufacturing", group: "Industrial & Engineering" },
  { value: "Construction & Engineering", group: "Industrial & Engineering" },
  { value: "Automotive", group: "Industrial & Engineering" },
  { value: "Aerospace & Defense", group: "Industrial & Engineering" },
  { value: "Energy & Utilities", group: "Industrial & Engineering" },
  { value: "Oil & Gas", group: "Industrial & Engineering" },
  { value: "Renewable Energy & CleanTech", group: "Industrial & Engineering" },
  { value: "Retail", group: "Consumer & Lifestyle" },
  { value: "Consumer Goods (CPG)", group: "Consumer & Lifestyle" },
  { value: "Food & Beverage", group: "Consumer & Lifestyle" },
  { value: "Hospitality & Tourism", group: "Consumer & Lifestyle" },
  { value: "Fashion & Apparel", group: "Consumer & Lifestyle" },
  { value: "Beauty & Personal Care", group: "Consumer & Lifestyle" },
  { value: "Fitness & Sports", group: "Consumer & Lifestyle" },
  { value: "Home & Interior Design", group: "Consumer & Lifestyle" },
  { value: "Pets & Animal Care", group: "Consumer & Lifestyle" },
  { value: "Agriculture & AgTech", group: "Specialized" },
  { value: "Logistics & Supply Chain", group: "Specialized" },
  { value: "Transportation", group: "Specialized" },
  { value: "Human Resources & Recruiting", group: "Specialized" },
  { value: "Environmental & Sustainability", group: "Specialized" },
  { value: "Cannabis & Hemp", group: "Specialized" },
  { value: "Crypto & Blockchain", group: "Specialized" },
  { value: "Other", group: "Specialized" },
];

export const INDUSTRY_GROUPS: string[] = Array.from(new Set(INDUSTRIES.map((i) => i.group)));
