#!/usr/bin/env tsx
/**
 * Captures the storage layer's method surface and the body of every method.
 *
 * Why this exists: B5 splits a 5,251-line `DatabaseStorage` class into domain
 * modules and composes them back into one `storage` object. Three things can go
 * wrong silently, and none of them are caught by `tsc`:
 *
 * 1. A method is dropped. `IStorage` declares 307 methods; if an implementation
 *    goes missing the object literal simply fails to satisfy the interface, which
 *    tsc does catch, but only if the interface is still complete. If a method is
 *    dropped from BOTH, nothing complains and callers break at runtime.
 * 2. Two domain modules define the same method name. Object spread resolves that
 *    silently: last one wins, and the loser's behaviour disappears.
 * 3. A method body changes during the move. A pure move must not alter behaviour,
 *    and a diff of a 5,000-line file is unreadable, so a per-method comparison is
 *    the only practical check.
 *
 * Bodies are compared with whitespace collapsed so reformatting does not raise a
 * false alarm, but any real edit does.
 *
 * The baseline is read from a git ref (default: `origin/main`, falling back to
 * `main`), NOT from a JSON file checked into the branch under audit. A baseline
 * file living inside `.audit/` is not a real ratchet: it is just more code the
 * same PR can edit, and the original B5 baseline
 * (`.audit/B5/storage-surface-before.json`, produced by this script) proves it -
 * `git log --follow` on that file shows it was generated by the same commit
 * (fd73edd, "shrink the platform catch-all and gate the surface in CI") that
 * both finished the decomposition AND wired the check into CI, after most of
 * the domain-extraction commits (087d1d3 through a827765) had already landed.
 * A baseline captured after the fact cannot catch anything that went missing
 * during the work it was meant to guard. Reading the baseline from `main`
 * instead fixes this: `main` does not yet contain this decomposition at all
 * (as of this fix), so comparing against it catches every regression the old
 * file-based baseline missed, and after this branch merges, `main` becomes a
 * baseline that no single future PR can rewrite from inside itself - it only
 * advances through reviewed merges.
 *
 * Caveat this trades in: rule 3 (unchanged method bodies) only makes sense
 * while a pure decomposition is in flight. Once B5 is fully merged, comparing
 * every future PR's storage bodies against a constantly-advancing `main`
 * would flag every ordinary bugfix to a storage method as a "problem" - there
 * is no PR-local way to update the baseline the way the old committed JSON
 * file allowed. This script (or at least the body-equality rule) should be
 * retired once the decomposition lands on `main`, not kept on as a permanent
 * gate.
 *
 * Usage:
 *   npx tsx scripts/storageSurface.ts > before.json
 *   npx tsx scripts/storageSurface.ts --check [git-ref]   (default origin/main)
 */

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function git(args: string[]): string {
  return execFileSync("git", args, { cwd: repoRoot, encoding: "utf8" });
}

/** First ref in the list that `git rev-parse` can actually resolve. */
function resolveRef(candidates: readonly string[]): string {
  for (const ref of candidates) {
    try {
      git(["rev-parse", "--verify", "--quiet", ref]);
      return ref;
    } catch {
      // try the next candidate
    }
  }
  throw new Error(`None of these refs resolve: ${candidates.join(", ")}`);
}

function readFileAtRef(ref: string, relPath: string): string | undefined {
  try {
    return git(["show", `${ref}:${relPath}`]);
  } catch {
    return undefined; // file did not exist at this ref
  }
}

/** `server/storage/*.ts` file paths (repo-relative, posix-separated) at a ref. */
function listStorageDirAtRef(ref: string): string[] {
  try {
    return git(["ls-tree", "-r", "--name-only", ref, "--", "server/storage"])
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line.endsWith(".ts"));
  } catch {
    return [];
  }
}

type Surface = {
  interfaceMethods: string[];
  implementations: Record<string, { body: string; source: string }>;
  duplicates: Array<{ name: string; sources: string[] }>;
};

function parseText(fileName: string, text: string): ts.SourceFile {
  return ts.createSourceFile(fileName, text, ts.ScriptTarget.Latest, true);
}

/** Reads repo files either off disk (the working tree) or out of a git ref. */
type SourceReader = {
  /** repo-relative posix path -> file text, or undefined if absent there */
  read(relPath: string): string | undefined;
  /** repo-relative posix paths of every `.ts` file directly under server/storage */
  storageDirFiles(): string[];
  describe(): string;
};

function workingTreeReader(): SourceReader {
  return {
    read(relPath) {
      const abs = path.join(repoRoot, ...relPath.split("/"));
      return fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : undefined;
    },
    storageDirFiles() {
      const dir = path.join(repoRoot, "server", "storage");
      if (!fs.existsSync(dir)) return [];
      return fs
        .readdirSync(dir, { withFileTypes: true })
        .filter((e) => e.isFile() && e.name.endsWith(".ts"))
        .map((e) => `server/storage/${e.name}`);
    },
    describe: () => "the working tree",
  };
}

function gitRefReader(ref: string): SourceReader {
  return {
    read: (relPath) => readFileAtRef(ref, relPath),
    storageDirFiles: () => listStorageDirAtRef(ref),
    describe: () => `git ref "${ref}"`,
  };
}

function objectLiteralInitializer(
  initializer: ts.Expression,
): ts.ObjectLiteralExpression | undefined {
  let expression = initializer;
  while (
    ts.isAsExpression(expression) ||
    ts.isParenthesizedExpression(expression) ||
    ts.isSatisfiesExpression(expression) ||
    ts.isTypeAssertionExpression(expression)
  ) {
    expression = expression.expression;
  }
  return ts.isObjectLiteralExpression(expression) ? expression : undefined;
}

/** Collapses whitespace so formatting churn does not read as a behaviour change. */
function normalise(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

/** Method names declared on `interface IStorage`. */
function interfaceMethods(reader: SourceReader): string[] {
  const text = reader.read("server/storage.ts");
  if (text === undefined) {
    throw new Error(`server/storage.ts does not exist at ${reader.describe()}`);
  }
  const source = parseText("server/storage.ts", text);
  const names: string[] = [];
  const visit = (node: ts.Node): void => {
    if (ts.isInterfaceDeclaration(node) && node.name.text === "IStorage") {
      for (const member of node.members) {
        if (
          (ts.isMethodSignature(member) || ts.isPropertySignature(member)) &&
          member.name &&
          ts.isIdentifier(member.name)
        ) {
          names.push(member.name.text);
        }
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(source);
  return names.sort();
}

/**
 * Every method implementation reachable from the storage layer, whether it lives
 * on the `DatabaseStorage` class or in a plain object literal such as
 * `export const brandStorage = { ... }`. Both shapes are in use.
 */
function implementations(reader: SourceReader): {
  map: Record<string, { body: string; source: string }>;
  dupes: Array<{ name: string; sources: string[] }>;
} {
  const relPaths = ["server/databaseStorage.ts", ...reader.storageDirFiles()];

  const map: Record<string, { body: string; source: string }> = {};
  const seen = new Map<string, string[]>();

  for (const rel of relPaths) {
    const text = reader.read(rel);
    if (text === undefined) continue;
    const source = parseText(rel, text);

    const record = (name: string, body: string): void => {
      seen.set(name, [...(seen.get(name) ?? []), rel]);
      map[name] = { body: normalise(body), source: rel };
    };

    const visit = (node: ts.Node): void => {
      // class DatabaseStorage { async foo() { ... } }
      if (ts.isClassDeclaration(node)) {
        for (const member of node.members) {
          if (ts.isMethodDeclaration(member) && member.name && ts.isIdentifier(member.name)) {
            record(member.name.text, member.body ? member.body.getText(source) : "");
          }
        }
      }
      // export const fooStorage = { async bar() { ... } }
      if (ts.isVariableStatement(node)) {
        for (const decl of node.declarationList.declarations) {
          if (!decl.initializer) continue;
          const initializer = objectLiteralInitializer(decl.initializer);
          if (!initializer) continue;
          for (const prop of initializer.properties) {
            if (ts.isMethodDeclaration(prop) && prop.name && ts.isIdentifier(prop.name)) {
              record(prop.name.text, prop.body ? prop.body.getText(source) : "");
            }
          }
        }
      }
      ts.forEachChild(node, visit);
    };
    visit(source);
  }

  const dupes = [...seen.entries()]
    .filter(([, sources]) => sources.length > 1)
    .map(([name, sources]) => ({ name, sources }));

  return { map, dupes };
}

function captureSurface(reader: SourceReader): Surface {
  const { map, dupes } = implementations(reader);
  return {
    interfaceMethods: interfaceMethods(reader),
    implementations: map,
    duplicates: dupes,
  };
}

const surface = captureSurface(workingTreeReader());

const checkIndex = process.argv.indexOf("--check");
if (checkIndex === -1) {
  console.log(JSON.stringify(surface, null, 1));
  process.exit(0);
}

// The ref to compare against defaults to origin/main, falling back to a local
// main - see the module comment for why this is a git ref and not a checked-in
// JSON file. An explicit ref (or a legacy baseline JSON path, for anyone with
// a saved `storage:surface > before.json` file lying around) can still be
// passed as the argument after --check.
const explicitTarget = process.argv[checkIndex + 1];
let before: Surface;
if (explicitTarget?.endsWith(".json")) {
  // A missing baseline file is an error, not a reason to fall through. Without
  // this, a stale invocation - the retired
  // `--check .audit/B5/storage-surface-before.json`, say - reached the branch
  // below and was handed to `git show <path>:server/storage.ts`, which fails
  // with a git error that says nothing about the real problem.
  if (!fs.existsSync(explicitTarget)) {
    console.error(
      `Baseline file not found: ${explicitTarget}\n` +
        `The committed .audit/B5 baseline was retired - it was generated by the same\n` +
        `commit that finished the decomposition, so it could not detect a loss during it.\n` +
        `Run with no argument to compare against origin/main, or pass a git ref.`,
    );
    process.exit(1);
  }
  before = JSON.parse(fs.readFileSync(explicitTarget, "utf8"));
} else {
  const ref = explicitTarget || resolveRef(["origin/main", "main"]);
  before = captureSurface(gitRefReader(ref));
  console.log(`Comparing against the storage surface at ${ref}.`);
}
const problems: string[] = [];

// 1. The interface must not change. 60 files depend on it.
const ifaceRemoved = before.interfaceMethods.filter((m) => !surface.interfaceMethods.includes(m));
const ifaceAdded = surface.interfaceMethods.filter((m) => !before.interfaceMethods.includes(m));
if (ifaceRemoved.length)
  problems.push(`IStorage lost ${ifaceRemoved.length} methods: ${ifaceRemoved.join(", ")}`);
if (ifaceAdded.length)
  problems.push(`IStorage gained ${ifaceAdded.length} methods: ${ifaceAdded.join(", ")}`);

// 2. Nothing may be implemented twice. Object spread resolves a clash silently.
if (surface.duplicates.length) {
  for (const d of surface.duplicates) {
    problems.push(
      `"${d.name}" is implemented in ${d.sources.length} files: ${d.sources.join(", ")}`,
    );
  }
}

// 3. Every method must still exist, with an unchanged body.
const beforeNames = Object.keys(before.implementations);
const afterNames = Object.keys(surface.implementations);
const implRemoved = beforeNames.filter((m) => !afterNames.includes(m));
const implAdded = afterNames.filter((m) => !beforeNames.includes(m));
if (implRemoved.length)
  problems.push(
    `${implRemoved.length} implementations disappeared: ${implRemoved.slice(0, 10).join(", ")}`,
  );
if (implAdded.length)
  problems.push(
    `${implAdded.length} implementations appeared: ${implAdded.slice(0, 10).join(", ")}`,
  );

// Only a method that MOVED and changed body is a problem. The predicate used
// to compare bodies alone while the message blamed a move, which was fine
// while the decomposition was in flight against a pre-decomposition baseline -
// nothing had moved yet on `main`, so any body difference was a move.
//
// That stopped being true once B5 landed on `main`. Comparing against an
// advancing baseline, a plain in-place bugfix to any storage method differs
// from `main` and failed the gate, blaming "a move that should not alter
// behaviour" when no file moved. That is a false positive with a misleading
// message, and it would have blocked ordinary work.
//
// Scoping it to moved methods restores the invariant the rule was written for -
// a pure relocation must not change behaviour - and makes the message true.
// Editing a method in place is a normal change and no longer trips it.
const changed = beforeNames
  .filter((m) => afterNames.includes(m))
  .filter((m) => before.implementations[m].source !== surface.implementations[m].source)
  .filter((m) => before.implementations[m].body !== surface.implementations[m].body);
if (changed.length) {
  problems.push(
    `${changed.length} method bodies changed during a move that should not alter behaviour:`,
  );
  for (const m of changed.slice(0, 10)) {
    problems.push(
      `    ${m}  (${before.implementations[m].source} -> ${surface.implementations[m].source})`,
    );
  }
}

const moved = beforeNames
  .filter((m) => afterNames.includes(m))
  .filter((m) => before.implementations[m].source !== surface.implementations[m].source).length;

if (problems.length === 0) {
  console.log(
    `Storage surface intact. ${surface.interfaceMethods.length} interface methods, ` +
      `${afterNames.length} implementations, ${moved} relocated, no duplicates, no body changed.`,
  );
  process.exit(0);
}

for (const p of problems) console.error(p);
console.error(
  "\nA decomposition must not change the interface, duplicate a method, or edit a body.",
);
process.exit(1);
