/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HealthRouteImport } from './routes/health'
import { Route as InternalPageRouteImport } from './routes/internal-page'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as V2PreviewRouteImport } from './routes/v2-preview'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppActRouteImport } from './routes/_app/act'
import { Route as AppAiIntelligenceRouteImport } from './routes/_app/ai-intelligence'
import { Route as AppAiVisibilityRouteImport } from './routes/_app/ai-visibility'
import { Route as AppArticlesRouteImport } from './routes/_app/articles'
import { Route as AppBrandFactSheetRouteImport } from './routes/_app/brand-fact-sheet'
import { Route as AppBrandsRouteImport } from './routes/_app/brands'
import { Route as AppCitationsRouteImport } from './routes/_app/citations'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppCompetitorsRouteImport } from './routes/_app/competitors'
import { Route as AppContentRouteImport } from './routes/_app/content'
import { Route as AppCrawlerCheckRouteImport } from './routes/_app/crawler-check'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDiagnoseRouteImport } from './routes/_app/diagnose'
import { Route as AppFaqManagerRouteImport } from './routes/_app/faq-manager'
import { Route as AppForgotPasswordRouteImport } from './routes/_app/forgot-password'
import { Route as AppGeoAnalyticsRouteImport } from './routes/_app/geo-analytics'
import { Route as AppGeoSignalsRouteImport } from './routes/_app/geo-signals'
import { Route as AppGeoToolsRouteImport } from './routes/_app/geo-tools'
import { Route as AppHome2RouteImport } from './routes/_app/home2'
import { Route as AppKeywordResearchRouteImport } from './routes/_app/keyword-research'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppMonitorRouteImport } from './routes/_app/monitor'
import { Route as AppOpportunitiesRouteImport } from './routes/_app/opportunities'
import { Route as AppPerceptionRouteImport } from './routes/_app/perception'
import { Route as AppPromptsRouteImport } from './routes/_app/prompts'
import { Route as AppRegisterRouteImport } from './routes/_app/register'
import { Route as AppReportRouteImport } from './routes/_app/report'
import { Route as AppResetPasswordRouteImport } from './routes/_app/reset-password'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSetupRouteImport } from './routes/_app/setup'
import { Route as AppSiteHealthRouteImport } from './routes/_app/site-health'
import { Route as AppV2RouteImport } from './routes/_app/v2'
import { Route as AppVerifyEmailRouteImport } from './routes/_app/verify-email'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as V2PreviewIndexRouteImport } from './routes/v2-preview.index'
import { Route as V2PreviewBoardRouteImport } from './routes/v2-preview.$board'
import { Route as WebhooksSplatRouteImport } from './routes/webhooks/$'
import { Route as AppAdminScrapeRouteImport } from './routes/_app/admin.scrape'
import { Route as AppContentArticleIdRouteImport } from './routes/_app/content.$articleId'
import { Route as AppPromptsIndexRouteImport } from './routes/_app/prompts.index'
import { Route as AppPromptsPromptIdRouteImport } from './routes/_app/prompts.$promptId'
import { Route as AppV2AgencyRouteImport } from './routes/_app/v2.agency'
import { Route as AppV2BrandFactsRouteImport } from './routes/_app/v2.brand-facts'
import { Route as AppV2DiagnosticsRouteImport } from './routes/_app/v2.diagnostics'
import { Route as AppV2GeoAssistantRouteImport } from './routes/_app/v2.geo-assistant'
import { Route as AppV2LearnRouteImport } from './routes/_app/v2.learn'
import { Route as AppV2MyWorkRouteImport } from './routes/_app/v2.my-work'
import { Route as AppV2NotificationsRouteImport } from './routes/_app/v2.notifications'
import { Route as AppV2OnboardingRouteImport } from './routes/_app/v2.onboarding'
import { Route as AppV2PlansRouteImport } from './routes/_app/v2.plans'
import { Route as AppV2SettingsRouteImport } from './routes/_app/v2.settings'
import { Route as AppV2SignInRouteImport } from './routes/_app/v2.sign-in'
import { Route as AppV2TodayRouteImport } from './routes/_app/v2.today'
import { Route as AppV2VisibilityRouteImport } from './routes/_app/v2.visibility'
import { Route as AppAdminScrapeRunIdRouteImport } from './routes/_app/admin.scrape.$runId'
import { Route as AppPromptsPromptIdIndexRouteImport } from './routes/_app/prompts.$promptId.index'
import { Route as AppPromptsPromptIdDiagnoseRouteImport } from './routes/_app/prompts.$promptId.diagnose'
import { Route as AppV2BrandFactsIndexRouteImport } from './routes/_app/v2.brand-facts.index'
import { Route as AppV2BrandFactsWorkspaceRouteImport } from './routes/_app/v2.brand-facts.workspace'
import { Route as AppV2DiagnosticsIndexRouteImport } from './routes/_app/v2.diagnostics.index'
import { Route as AppV2DiagnosticsCompetitorGapRouteImport } from './routes/_app/v2.diagnostics.competitor-gap'
import { Route as AppV2DiagnosticsGeoSignalsRouteImport } from './routes/_app/v2.diagnostics.geo-signals'
import { Route as AppV2DiagnosticsPerceptionRouteImport } from './routes/_app/v2.diagnostics.perception'
import { Route as AppV2DiagnosticsPromptsRouteImport } from './routes/_app/v2.diagnostics.prompts'
import { Route as AppV2DiagnosticsSiteHealthRouteImport } from './routes/_app/v2.diagnostics.site-health'
import { Route as AppV2MyWorkIndexRouteImport } from './routes/_app/v2.my-work.index'
import { Route as AppV2MyWorkContentOpportunitiesRouteImport } from './routes/_app/v2.my-work.content-opportunities'
import { Route as AppV2MyWorkEarnedMediaRouteImport } from './routes/_app/v2.my-work.earned-media'
import { Route as AppV2MyWorkQueueRouteImport } from './routes/_app/v2.my-work.queue'
import { Route as AppV2OnboardingBaselineRouteImport } from './routes/_app/v2.onboarding.baseline'
import { Route as AppV2OnboardingBaselineReviewRouteImport } from './routes/_app/v2.onboarding.baseline-review'
import { Route as AppV2OnboardingFactsRouteImport } from './routes/_app/v2.onboarding.facts'
import { Route as AppV2OnboardingInspectionRouteImport } from './routes/_app/v2.onboarding.inspection'
import { Route as AppV2OnboardingQuestionsRouteImport } from './routes/_app/v2.onboarding.questions'
import { Route as AppV2OnboardingStartRouteImport } from './routes/_app/v2.onboarding.start'
import { Route as AppV2SettingsIndexRouteImport } from './routes/_app/v2.settings.index'
import { Route as AppV2SettingsBillingRouteImport } from './routes/_app/v2.settings.billing'
import { Route as AppV2SettingsIntegrationsRouteImport } from './routes/_app/v2.settings.integrations'
import { Route as AppV2SettingsTeamRouteImport } from './routes/_app/v2.settings.team'
import { Route as AppV2VisibilityIndexRouteImport } from './routes/_app/v2.visibility.index'
import { Route as AppV2VisibilityCitationsRouteImport } from './routes/_app/v2.visibility.citations'
import { Route as AppV2VisibilityEvidenceRouteImport } from './routes/_app/v2.visibility.evidence'
import { Route as AppV2VisibilityOutcomeReviewRouteImport } from './routes/_app/v2.visibility.outcome-review'
import { Route as AppV2VisibilityQuestionsRouteImport } from './routes/_app/v2.visibility.questions'
import { Route as AppV2VisibilityReportRouteImport } from './routes/_app/v2.visibility.report'
import { Route as AppV2VisibilityResultsRouteImport } from './routes/_app/v2.visibility.results'
import { Route as AppV2MyWorkTasksTaskIdRouteImport } from './routes/_app/v2.my-work.tasks.$taskId'
import { Route as AppV2VisibilityQuestionsQuestionIdRouteImport } from './routes/_app/v2.visibility.questions.$questionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPageRoute = InternalPageRouteImport.update({
  id: '/internal-page',
  path: '/internal-page',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const V2PreviewRoute = V2PreviewRouteImport.update({
  id: '/v2-preview',
  path: '/v2-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppActRoute = AppActRouteImport.update({
  id: '/act',
  path: '/act',
  getParentRoute: () => AppRoute,
} as any)
const AppAiIntelligenceRoute = AppAiIntelligenceRouteImport.update({
  id: '/ai-intelligence',
  path: '/ai-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppAiVisibilityRoute = AppAiVisibilityRouteImport.update({
  id: '/ai-visibility',
  path: '/ai-visibility',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesRoute = AppArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandFactSheetRoute = AppBrandFactSheetRouteImport.update({
  id: '/brand-fact-sheet',
  path: '/brand-fact-sheet',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsRoute = AppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRoute,
} as any)
const AppCitationsRoute = AppCitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppCrawlerCheckRoute = AppCrawlerCheckRouteImport.update({
  id: '/crawler-check',
  path: '/crawler-check',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnoseRoute = AppDiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => AppRoute,
} as any)
const AppFaqManagerRoute = AppFaqManagerRouteImport.update({
  id: '/faq-manager',
  path: '/faq-manager',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoAnalyticsRoute = AppGeoAnalyticsRouteImport.update({
  id: '/geo-analytics',
  path: '/geo-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoSignalsRoute = AppGeoSignalsRouteImport.update({
  id: '/geo-signals',
  path: '/geo-signals',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoToolsRoute = AppGeoToolsRouteImport.update({
  id: '/geo-tools',
  path: '/geo-tools',
  getParentRoute: () => AppRoute,
} as any)
const AppHome2Route = AppHome2RouteImport.update({
  id: '/home2',
  path: '/home2',
  getParentRoute: () => AppRoute,
} as any)
const AppKeywordResearchRoute = AppKeywordResearchRouteImport.update({
  id: '/keyword-research',
  path: '/keyword-research',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorRoute = AppMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppPerceptionRoute = AppPerceptionRouteImport.update({
  id: '/perception',
  path: '/perception',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppResetPasswordRoute = AppResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteHealthRoute = AppSiteHealthRouteImport.update({
  id: '/site-health',
  path: '/site-health',
  getParentRoute: () => AppRoute,
} as any)
const AppV2Route = AppV2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyEmailRoute = AppVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V2PreviewIndexRoute = V2PreviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2PreviewRoute,
} as any)
const V2PreviewBoardRoute = V2PreviewBoardRouteImport.update({
  id: '/$board',
  path: '/$board',
  getParentRoute: () => V2PreviewRoute,
} as any)
const WebhooksSplatRoute = WebhooksSplatRouteImport.update({
  id: '/webhooks/$',
  path: '/webhooks/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminScrapeRoute = AppAdminScrapeRouteImport.update({
  id: '/admin/scrape',
  path: '/admin/scrape',
  getParentRoute: () => AppRoute,
} as any)
const AppContentArticleIdRoute = AppContentArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => AppContentRoute,
} as any)
const AppPromptsIndexRoute = AppPromptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPromptsRoute,
} as any)
const AppPromptsPromptIdRoute = AppPromptsPromptIdRouteImport.update({
  id: '/$promptId',
  path: '/$promptId',
  getParentRoute: () => AppPromptsRoute,
} as any)
const AppV2AgencyRoute = AppV2AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2BrandFactsRoute = AppV2BrandFactsRouteImport.update({
  id: '/brand-facts',
  path: '/brand-facts',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2DiagnosticsRoute = AppV2DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2GeoAssistantRoute = AppV2GeoAssistantRouteImport.update({
  id: '/geo-assistant',
  path: '/geo-assistant',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2LearnRoute = AppV2LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2MyWorkRoute = AppV2MyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2NotificationsRoute = AppV2NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2OnboardingRoute = AppV2OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2PlansRoute = AppV2PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2SettingsRoute = AppV2SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2SignInRoute = AppV2SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2TodayRoute = AppV2TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2VisibilityRoute = AppV2VisibilityRouteImport.update({
  id: '/visibility',
  path: '/visibility',
  getParentRoute: () => AppV2Route,
} as any)
const AppAdminScrapeRunIdRoute = AppAdminScrapeRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AppAdminScrapeRoute,
} as any)
const AppPromptsPromptIdIndexRoute = AppPromptsPromptIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPromptsPromptIdRoute,
} as any)
const AppPromptsPromptIdDiagnoseRoute =
  AppPromptsPromptIdDiagnoseRouteImport.update({
    id: '/diagnose',
    path: '/diagnose',
    getParentRoute: () => AppPromptsPromptIdRoute,
  } as any)
const AppV2BrandFactsIndexRoute = AppV2BrandFactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppV2BrandFactsRoute,
} as any)
const AppV2BrandFactsWorkspaceRoute =
  AppV2BrandFactsWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AppV2BrandFactsRoute,
  } as any)
const AppV2DiagnosticsIndexRoute = AppV2DiagnosticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppV2DiagnosticsRoute,
} as any)
const AppV2DiagnosticsCompetitorGapRoute =
  AppV2DiagnosticsCompetitorGapRouteImport.update({
    id: '/competitor-gap',
    path: '/competitor-gap',
    getParentRoute: () => AppV2DiagnosticsRoute,
  } as any)
const AppV2DiagnosticsGeoSignalsRoute =
  AppV2DiagnosticsGeoSignalsRouteImport.update({
    id: '/geo-signals',
    path: '/geo-signals',
    getParentRoute: () => AppV2DiagnosticsRoute,
  } as any)
const AppV2DiagnosticsPerceptionRoute =
  AppV2DiagnosticsPerceptionRouteImport.update({
    id: '/perception',
    path: '/perception',
    getParentRoute: () => AppV2DiagnosticsRoute,
  } as any)
const AppV2DiagnosticsPromptsRoute = AppV2DiagnosticsPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppV2DiagnosticsRoute,
} as any)
const AppV2DiagnosticsSiteHealthRoute =
  AppV2DiagnosticsSiteHealthRouteImport.update({
    id: '/site-health',
    path: '/site-health',
    getParentRoute: () => AppV2DiagnosticsRoute,
  } as any)
const AppV2MyWorkIndexRoute = AppV2MyWorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppV2MyWorkRoute,
} as any)
const AppV2MyWorkContentOpportunitiesRoute =
  AppV2MyWorkContentOpportunitiesRouteImport.update({
    id: '/content-opportunities',
    path: '/content-opportunities',
    getParentRoute: () => AppV2MyWorkRoute,
  } as any)
const AppV2MyWorkEarnedMediaRoute = AppV2MyWorkEarnedMediaRouteImport.update({
  id: '/earned-media',
  path: '/earned-media',
  getParentRoute: () => AppV2MyWorkRoute,
} as any)
const AppV2MyWorkQueueRoute = AppV2MyWorkQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppV2MyWorkRoute,
} as any)
const AppV2OnboardingBaselineRoute = AppV2OnboardingBaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => AppV2OnboardingRoute,
} as any)
const AppV2OnboardingBaselineReviewRoute =
  AppV2OnboardingBaselineReviewRouteImport.update({
    id: '/baseline-review',
    path: '/baseline-review',
    getParentRoute: () => AppV2OnboardingRoute,
  } as any)
const AppV2OnboardingFactsRoute = AppV2OnboardingFactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => AppV2OnboardingRoute,
} as any)
const AppV2OnboardingInspectionRoute =
  AppV2OnboardingInspectionRouteImport.update({
    id: '/inspection',
    path: '/inspection',
    getParentRoute: () => AppV2OnboardingRoute,
  } as any)
const AppV2OnboardingQuestionsRoute =
  AppV2OnboardingQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AppV2OnboardingRoute,
  } as any)
const AppV2OnboardingStartRoute = AppV2OnboardingStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AppV2OnboardingRoute,
} as any)
const AppV2SettingsIndexRoute = AppV2SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppV2SettingsRoute,
} as any)
const AppV2SettingsBillingRoute = AppV2SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppV2SettingsRoute,
} as any)
const AppV2SettingsIntegrationsRoute =
  AppV2SettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppV2SettingsRoute,
  } as any)
const AppV2SettingsTeamRoute = AppV2SettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppV2SettingsRoute,
} as any)
const AppV2VisibilityIndexRoute = AppV2VisibilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppV2VisibilityRoute,
} as any)
const AppV2VisibilityCitationsRoute =
  AppV2VisibilityCitationsRouteImport.update({
    id: '/citations',
    path: '/citations',
    getParentRoute: () => AppV2VisibilityRoute,
  } as any)
const AppV2VisibilityEvidenceRoute = AppV2VisibilityEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppV2VisibilityRoute,
} as any)
const AppV2VisibilityOutcomeReviewRoute =
  AppV2VisibilityOutcomeReviewRouteImport.update({
    id: '/outcome-review',
    path: '/outcome-review',
    getParentRoute: () => AppV2VisibilityRoute,
  } as any)
const AppV2VisibilityQuestionsRoute =
  AppV2VisibilityQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AppV2VisibilityRoute,
  } as any)
const AppV2VisibilityReportRoute = AppV2VisibilityReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppV2VisibilityRoute,
} as any)
const AppV2VisibilityResultsRoute = AppV2VisibilityResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppV2VisibilityRoute,
} as any)
const AppV2MyWorkTasksTaskIdRoute = AppV2MyWorkTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppV2MyWorkRoute,
} as any)
const AppV2VisibilityQuestionsQuestionIdRoute =
  AppV2VisibilityQuestionsQuestionIdRouteImport.update({
    id: '/$questionId',
    path: '/$questionId',
    getParentRoute: () => AppV2VisibilityQuestionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/health': typeof HealthRoute
  '/internal-page': typeof InternalPageRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/v2-preview': typeof V2PreviewRouteWithChildren
  '/$': typeof AppSplatRoute
  '/act': typeof AppActRoute
  '/ai-intelligence': typeof AppAiIntelligenceRoute
  '/ai-visibility': typeof AppAiVisibilityRoute
  '/articles': typeof AppArticlesRoute
  '/brand-fact-sheet': typeof AppBrandFactSheetRoute
  '/brands': typeof AppBrandsRoute
  '/citations': typeof AppCitationsRoute
  '/community': typeof AppCommunityRoute
  '/competitors': typeof AppCompetitorsRoute
  '/content': typeof AppContentRouteWithChildren
  '/crawler-check': typeof AppCrawlerCheckRoute
  '/dashboard': typeof AppDashboardRoute
  '/diagnose': typeof AppDiagnoseRoute
  '/faq-manager': typeof AppFaqManagerRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/geo-analytics': typeof AppGeoAnalyticsRoute
  '/geo-signals': typeof AppGeoSignalsRoute
  '/geo-tools': typeof AppGeoToolsRoute
  '/home2': typeof AppHome2Route
  '/keyword-research': typeof AppKeywordResearchRoute
  '/login': typeof AppLoginRoute
  '/monitor': typeof AppMonitorRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/perception': typeof AppPerceptionRoute
  '/prompts': typeof AppPromptsRouteWithChildren
  '/register': typeof AppRegisterRoute
  '/report': typeof AppReportRoute
  '/reset-password': typeof AppResetPasswordRoute
  '/settings': typeof AppSettingsRoute
  '/setup': typeof AppSetupRoute
  '/site-health': typeof AppSiteHealthRoute
  '/v2': typeof AppV2RouteWithChildren
  '/verify-email': typeof AppVerifyEmailRoute
  '/welcome': typeof AppWelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/v2-preview/$board': typeof V2PreviewBoardRoute
  '/webhooks/$': typeof WebhooksSplatRoute
  '/v2-preview/': typeof V2PreviewIndexRoute
  '/admin/scrape': typeof AppAdminScrapeRouteWithChildren
  '/content/$articleId': typeof AppContentArticleIdRoute
  '/prompts/$promptId': typeof AppPromptsPromptIdRouteWithChildren
  '/v2/agency': typeof AppV2AgencyRoute
  '/v2/brand-facts': typeof AppV2BrandFactsRouteWithChildren
  '/v2/diagnostics': typeof AppV2DiagnosticsRouteWithChildren
  '/v2/geo-assistant': typeof AppV2GeoAssistantRoute
  '/v2/learn': typeof AppV2LearnRoute
  '/v2/my-work': typeof AppV2MyWorkRouteWithChildren
  '/v2/notifications': typeof AppV2NotificationsRoute
  '/v2/onboarding': typeof AppV2OnboardingRouteWithChildren
  '/v2/plans': typeof AppV2PlansRoute
  '/v2/settings': typeof AppV2SettingsRouteWithChildren
  '/v2/sign-in': typeof AppV2SignInRoute
  '/v2/today': typeof AppV2TodayRoute
  '/v2/visibility': typeof AppV2VisibilityRouteWithChildren
  '/prompts/': typeof AppPromptsIndexRoute
  '/admin/scrape/$runId': typeof AppAdminScrapeRunIdRoute
  '/prompts/$promptId/diagnose': typeof AppPromptsPromptIdDiagnoseRoute
  '/v2/brand-facts/workspace': typeof AppV2BrandFactsWorkspaceRoute
  '/v2/diagnostics/competitor-gap': typeof AppV2DiagnosticsCompetitorGapRoute
  '/v2/diagnostics/geo-signals': typeof AppV2DiagnosticsGeoSignalsRoute
  '/v2/diagnostics/perception': typeof AppV2DiagnosticsPerceptionRoute
  '/v2/diagnostics/prompts': typeof AppV2DiagnosticsPromptsRoute
  '/v2/diagnostics/site-health': typeof AppV2DiagnosticsSiteHealthRoute
  '/v2/my-work/content-opportunities': typeof AppV2MyWorkContentOpportunitiesRoute
  '/v2/my-work/earned-media': typeof AppV2MyWorkEarnedMediaRoute
  '/v2/my-work/queue': typeof AppV2MyWorkQueueRoute
  '/v2/onboarding/baseline': typeof AppV2OnboardingBaselineRoute
  '/v2/onboarding/baseline-review': typeof AppV2OnboardingBaselineReviewRoute
  '/v2/onboarding/facts': typeof AppV2OnboardingFactsRoute
  '/v2/onboarding/inspection': typeof AppV2OnboardingInspectionRoute
  '/v2/onboarding/questions': typeof AppV2OnboardingQuestionsRoute
  '/v2/onboarding/start': typeof AppV2OnboardingStartRoute
  '/v2/settings/billing': typeof AppV2SettingsBillingRoute
  '/v2/settings/integrations': typeof AppV2SettingsIntegrationsRoute
  '/v2/settings/team': typeof AppV2SettingsTeamRoute
  '/v2/visibility/citations': typeof AppV2VisibilityCitationsRoute
  '/v2/visibility/evidence': typeof AppV2VisibilityEvidenceRoute
  '/v2/visibility/outcome-review': typeof AppV2VisibilityOutcomeReviewRoute
  '/v2/visibility/questions': typeof AppV2VisibilityQuestionsRouteWithChildren
  '/v2/visibility/report': typeof AppV2VisibilityReportRoute
  '/v2/visibility/results': typeof AppV2VisibilityResultsRoute
  '/prompts/$promptId/': typeof AppPromptsPromptIdIndexRoute
  '/v2/brand-facts/': typeof AppV2BrandFactsIndexRoute
  '/v2/diagnostics/': typeof AppV2DiagnosticsIndexRoute
  '/v2/my-work/': typeof AppV2MyWorkIndexRoute
  '/v2/settings/': typeof AppV2SettingsIndexRoute
  '/v2/visibility/': typeof AppV2VisibilityIndexRoute
  '/v2/my-work/tasks/$taskId': typeof AppV2MyWorkTasksTaskIdRoute
  '/v2/visibility/questions/$questionId': typeof AppV2VisibilityQuestionsQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/health': typeof HealthRoute
  '/internal-page': typeof InternalPageRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/$': typeof AppSplatRoute
  '/act': typeof AppActRoute
  '/ai-intelligence': typeof AppAiIntelligenceRoute
  '/ai-visibility': typeof AppAiVisibilityRoute
  '/articles': typeof AppArticlesRoute
  '/brand-fact-sheet': typeof AppBrandFactSheetRoute
  '/brands': typeof AppBrandsRoute
  '/citations': typeof AppCitationsRoute
  '/community': typeof AppCommunityRoute
  '/competitors': typeof AppCompetitorsRoute
  '/content': typeof AppContentRouteWithChildren
  '/crawler-check': typeof AppCrawlerCheckRoute
  '/dashboard': typeof AppDashboardRoute
  '/diagnose': typeof AppDiagnoseRoute
  '/faq-manager': typeof AppFaqManagerRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/geo-analytics': typeof AppGeoAnalyticsRoute
  '/geo-signals': typeof AppGeoSignalsRoute
  '/geo-tools': typeof AppGeoToolsRoute
  '/home2': typeof AppHome2Route
  '/keyword-research': typeof AppKeywordResearchRoute
  '/login': typeof AppLoginRoute
  '/monitor': typeof AppMonitorRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/perception': typeof AppPerceptionRoute
  '/register': typeof AppRegisterRoute
  '/report': typeof AppReportRoute
  '/reset-password': typeof AppResetPasswordRoute
  '/settings': typeof AppSettingsRoute
  '/setup': typeof AppSetupRoute
  '/site-health': typeof AppSiteHealthRoute
  '/v2': typeof AppV2RouteWithChildren
  '/verify-email': typeof AppVerifyEmailRoute
  '/welcome': typeof AppWelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/v2-preview/$board': typeof V2PreviewBoardRoute
  '/webhooks/$': typeof WebhooksSplatRoute
  '/v2-preview': typeof V2PreviewIndexRoute
  '/admin/scrape': typeof AppAdminScrapeRouteWithChildren
  '/content/$articleId': typeof AppContentArticleIdRoute
  '/v2/agency': typeof AppV2AgencyRoute
  '/v2/geo-assistant': typeof AppV2GeoAssistantRoute
  '/v2/learn': typeof AppV2LearnRoute
  '/v2/notifications': typeof AppV2NotificationsRoute
  '/v2/onboarding': typeof AppV2OnboardingRouteWithChildren
  '/v2/plans': typeof AppV2PlansRoute
  '/v2/sign-in': typeof AppV2SignInRoute
  '/v2/today': typeof AppV2TodayRoute
  '/prompts': typeof AppPromptsIndexRoute
  '/admin/scrape/$runId': typeof AppAdminScrapeRunIdRoute
  '/prompts/$promptId/diagnose': typeof AppPromptsPromptIdDiagnoseRoute
  '/v2/brand-facts/workspace': typeof AppV2BrandFactsWorkspaceRoute
  '/v2/diagnostics/competitor-gap': typeof AppV2DiagnosticsCompetitorGapRoute
  '/v2/diagnostics/geo-signals': typeof AppV2DiagnosticsGeoSignalsRoute
  '/v2/diagnostics/perception': typeof AppV2DiagnosticsPerceptionRoute
  '/v2/diagnostics/prompts': typeof AppV2DiagnosticsPromptsRoute
  '/v2/diagnostics/site-health': typeof AppV2DiagnosticsSiteHealthRoute
  '/v2/my-work/content-opportunities': typeof AppV2MyWorkContentOpportunitiesRoute
  '/v2/my-work/earned-media': typeof AppV2MyWorkEarnedMediaRoute
  '/v2/my-work/queue': typeof AppV2MyWorkQueueRoute
  '/v2/onboarding/baseline': typeof AppV2OnboardingBaselineRoute
  '/v2/onboarding/baseline-review': typeof AppV2OnboardingBaselineReviewRoute
  '/v2/onboarding/facts': typeof AppV2OnboardingFactsRoute
  '/v2/onboarding/inspection': typeof AppV2OnboardingInspectionRoute
  '/v2/onboarding/questions': typeof AppV2OnboardingQuestionsRoute
  '/v2/onboarding/start': typeof AppV2OnboardingStartRoute
  '/v2/settings/billing': typeof AppV2SettingsBillingRoute
  '/v2/settings/integrations': typeof AppV2SettingsIntegrationsRoute
  '/v2/settings/team': typeof AppV2SettingsTeamRoute
  '/v2/visibility/citations': typeof AppV2VisibilityCitationsRoute
  '/v2/visibility/evidence': typeof AppV2VisibilityEvidenceRoute
  '/v2/visibility/outcome-review': typeof AppV2VisibilityOutcomeReviewRoute
  '/v2/visibility/questions': typeof AppV2VisibilityQuestionsRouteWithChildren
  '/v2/visibility/report': typeof AppV2VisibilityReportRoute
  '/v2/visibility/results': typeof AppV2VisibilityResultsRoute
  '/prompts/$promptId': typeof AppPromptsPromptIdIndexRoute
  '/v2/brand-facts': typeof AppV2BrandFactsIndexRoute
  '/v2/diagnostics': typeof AppV2DiagnosticsIndexRoute
  '/v2/my-work': typeof AppV2MyWorkIndexRoute
  '/v2/settings': typeof AppV2SettingsIndexRoute
  '/v2/visibility': typeof AppV2VisibilityIndexRoute
  '/v2/my-work/tasks/$taskId': typeof AppV2MyWorkTasksTaskIdRoute
  '/v2/visibility/questions/$questionId': typeof AppV2VisibilityQuestionsQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/glossary': typeof GlossaryRoute
  '/health': typeof HealthRoute
  '/internal-page': typeof InternalPageRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/v2-preview': typeof V2PreviewRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_app/act': typeof AppActRoute
  '/_app/ai-intelligence': typeof AppAiIntelligenceRoute
  '/_app/ai-visibility': typeof AppAiVisibilityRoute
  '/_app/articles': typeof AppArticlesRoute
  '/_app/brand-fact-sheet': typeof AppBrandFactSheetRoute
  '/_app/brands': typeof AppBrandsRoute
  '/_app/citations': typeof AppCitationsRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/competitors': typeof AppCompetitorsRoute
  '/_app/content': typeof AppContentRouteWithChildren
  '/_app/crawler-check': typeof AppCrawlerCheckRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/diagnose': typeof AppDiagnoseRoute
  '/_app/faq-manager': typeof AppFaqManagerRoute
  '/_app/forgot-password': typeof AppForgotPasswordRoute
  '/_app/geo-analytics': typeof AppGeoAnalyticsRoute
  '/_app/geo-signals': typeof AppGeoSignalsRoute
  '/_app/geo-tools': typeof AppGeoToolsRoute
  '/_app/home2': typeof AppHome2Route
  '/_app/keyword-research': typeof AppKeywordResearchRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/monitor': typeof AppMonitorRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/perception': typeof AppPerceptionRoute
  '/_app/prompts': typeof AppPromptsRouteWithChildren
  '/_app/register': typeof AppRegisterRoute
  '/_app/report': typeof AppReportRoute
  '/_app/reset-password': typeof AppResetPasswordRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/site-health': typeof AppSiteHealthRoute
  '/_app/v2': typeof AppV2RouteWithChildren
  '/_app/verify-email': typeof AppVerifyEmailRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/v2-preview/$board': typeof V2PreviewBoardRoute
  '/webhooks/$': typeof WebhooksSplatRoute
  '/v2-preview/': typeof V2PreviewIndexRoute
  '/_app/admin/scrape': typeof AppAdminScrapeRouteWithChildren
  '/_app/content/$articleId': typeof AppContentArticleIdRoute
  '/_app/prompts/$promptId': typeof AppPromptsPromptIdRouteWithChildren
  '/_app/v2/agency': typeof AppV2AgencyRoute
  '/_app/v2/brand-facts': typeof AppV2BrandFactsRouteWithChildren
  '/_app/v2/diagnostics': typeof AppV2DiagnosticsRouteWithChildren
  '/_app/v2/geo-assistant': typeof AppV2GeoAssistantRoute
  '/_app/v2/learn': typeof AppV2LearnRoute
  '/_app/v2/my-work': typeof AppV2MyWorkRouteWithChildren
  '/_app/v2/notifications': typeof AppV2NotificationsRoute
  '/_app/v2/onboarding': typeof AppV2OnboardingRouteWithChildren
  '/_app/v2/plans': typeof AppV2PlansRoute
  '/_app/v2/settings': typeof AppV2SettingsRouteWithChildren
  '/_app/v2/sign-in': typeof AppV2SignInRoute
  '/_app/v2/today': typeof AppV2TodayRoute
  '/_app/v2/visibility': typeof AppV2VisibilityRouteWithChildren
  '/_app/prompts/': typeof AppPromptsIndexRoute
  '/_app/admin/scrape/$runId': typeof AppAdminScrapeRunIdRoute
  '/_app/prompts/$promptId/diagnose': typeof AppPromptsPromptIdDiagnoseRoute
  '/_app/v2/brand-facts/workspace': typeof AppV2BrandFactsWorkspaceRoute
  '/_app/v2/diagnostics/competitor-gap': typeof AppV2DiagnosticsCompetitorGapRoute
  '/_app/v2/diagnostics/geo-signals': typeof AppV2DiagnosticsGeoSignalsRoute
  '/_app/v2/diagnostics/perception': typeof AppV2DiagnosticsPerceptionRoute
  '/_app/v2/diagnostics/prompts': typeof AppV2DiagnosticsPromptsRoute
  '/_app/v2/diagnostics/site-health': typeof AppV2DiagnosticsSiteHealthRoute
  '/_app/v2/my-work/content-opportunities': typeof AppV2MyWorkContentOpportunitiesRoute
  '/_app/v2/my-work/earned-media': typeof AppV2MyWorkEarnedMediaRoute
  '/_app/v2/my-work/queue': typeof AppV2MyWorkQueueRoute
  '/_app/v2/onboarding/baseline': typeof AppV2OnboardingBaselineRoute
  '/_app/v2/onboarding/baseline-review': typeof AppV2OnboardingBaselineReviewRoute
  '/_app/v2/onboarding/facts': typeof AppV2OnboardingFactsRoute
  '/_app/v2/onboarding/inspection': typeof AppV2OnboardingInspectionRoute
  '/_app/v2/onboarding/questions': typeof AppV2OnboardingQuestionsRoute
  '/_app/v2/onboarding/start': typeof AppV2OnboardingStartRoute
  '/_app/v2/settings/billing': typeof AppV2SettingsBillingRoute
  '/_app/v2/settings/integrations': typeof AppV2SettingsIntegrationsRoute
  '/_app/v2/settings/team': typeof AppV2SettingsTeamRoute
  '/_app/v2/visibility/citations': typeof AppV2VisibilityCitationsRoute
  '/_app/v2/visibility/evidence': typeof AppV2VisibilityEvidenceRoute
  '/_app/v2/visibility/outcome-review': typeof AppV2VisibilityOutcomeReviewRoute
  '/_app/v2/visibility/questions': typeof AppV2VisibilityQuestionsRouteWithChildren
  '/_app/v2/visibility/report': typeof AppV2VisibilityReportRoute
  '/_app/v2/visibility/results': typeof AppV2VisibilityResultsRoute
  '/_app/prompts/$promptId/': typeof AppPromptsPromptIdIndexRoute
  '/_app/v2/brand-facts/': typeof AppV2BrandFactsIndexRoute
  '/_app/v2/diagnostics/': typeof AppV2DiagnosticsIndexRoute
  '/_app/v2/my-work/': typeof AppV2MyWorkIndexRoute
  '/_app/v2/settings/': typeof AppV2SettingsIndexRoute
  '/_app/v2/visibility/': typeof AppV2VisibilityIndexRoute
  '/_app/v2/my-work/tasks/$taskId': typeof AppV2MyWorkTasksTaskIdRoute
  '/_app/v2/visibility/questions/$questionId': typeof AppV2VisibilityQuestionsQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/glossary'
    | '/health'
    | '/internal-page'
    | '/pricing'
    | '/privacy'
    | '/v2-preview'
    | '/$'
    | '/act'
    | '/ai-intelligence'
    | '/ai-visibility'
    | '/articles'
    | '/brand-fact-sheet'
    | '/brands'
    | '/citations'
    | '/community'
    | '/competitors'
    | '/content'
    | '/crawler-check'
    | '/dashboard'
    | '/diagnose'
    | '/faq-manager'
    | '/forgot-password'
    | '/geo-analytics'
    | '/geo-signals'
    | '/geo-tools'
    | '/home2'
    | '/keyword-research'
    | '/login'
    | '/monitor'
    | '/opportunities'
    | '/perception'
    | '/prompts'
    | '/register'
    | '/report'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/site-health'
    | '/v2'
    | '/verify-email'
    | '/welcome'
    | '/api/$'
    | '/v2-preview/$board'
    | '/webhooks/$'
    | '/v2-preview/'
    | '/admin/scrape'
    | '/content/$articleId'
    | '/prompts/$promptId'
    | '/v2/agency'
    | '/v2/brand-facts'
    | '/v2/diagnostics'
    | '/v2/geo-assistant'
    | '/v2/learn'
    | '/v2/my-work'
    | '/v2/notifications'
    | '/v2/onboarding'
    | '/v2/plans'
    | '/v2/settings'
    | '/v2/sign-in'
    | '/v2/today'
    | '/v2/visibility'
    | '/prompts/'
    | '/admin/scrape/$runId'
    | '/prompts/$promptId/diagnose'
    | '/v2/brand-facts/workspace'
    | '/v2/diagnostics/competitor-gap'
    | '/v2/diagnostics/geo-signals'
    | '/v2/diagnostics/perception'
    | '/v2/diagnostics/prompts'
    | '/v2/diagnostics/site-health'
    | '/v2/my-work/content-opportunities'
    | '/v2/my-work/earned-media'
    | '/v2/my-work/queue'
    | '/v2/onboarding/baseline'
    | '/v2/onboarding/baseline-review'
    | '/v2/onboarding/facts'
    | '/v2/onboarding/inspection'
    | '/v2/onboarding/questions'
    | '/v2/onboarding/start'
    | '/v2/settings/billing'
    | '/v2/settings/integrations'
    | '/v2/settings/team'
    | '/v2/visibility/citations'
    | '/v2/visibility/evidence'
    | '/v2/visibility/outcome-review'
    | '/v2/visibility/questions'
    | '/v2/visibility/report'
    | '/v2/visibility/results'
    | '/prompts/$promptId/'
    | '/v2/brand-facts/'
    | '/v2/diagnostics/'
    | '/v2/my-work/'
    | '/v2/settings/'
    | '/v2/visibility/'
    | '/v2/my-work/tasks/$taskId'
    | '/v2/visibility/questions/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/glossary'
    | '/health'
    | '/internal-page'
    | '/pricing'
    | '/privacy'
    | '/$'
    | '/act'
    | '/ai-intelligence'
    | '/ai-visibility'
    | '/articles'
    | '/brand-fact-sheet'
    | '/brands'
    | '/citations'
    | '/community'
    | '/competitors'
    | '/content'
    | '/crawler-check'
    | '/dashboard'
    | '/diagnose'
    | '/faq-manager'
    | '/forgot-password'
    | '/geo-analytics'
    | '/geo-signals'
    | '/geo-tools'
    | '/home2'
    | '/keyword-research'
    | '/login'
    | '/monitor'
    | '/opportunities'
    | '/perception'
    | '/register'
    | '/report'
    | '/reset-password'
    | '/settings'
    | '/setup'
    | '/site-health'
    | '/v2'
    | '/verify-email'
    | '/welcome'
    | '/api/$'
    | '/v2-preview/$board'
    | '/webhooks/$'
    | '/v2-preview'
    | '/admin/scrape'
    | '/content/$articleId'
    | '/v2/agency'
    | '/v2/geo-assistant'
    | '/v2/learn'
    | '/v2/notifications'
    | '/v2/onboarding'
    | '/v2/plans'
    | '/v2/sign-in'
    | '/v2/today'
    | '/prompts'
    | '/admin/scrape/$runId'
    | '/prompts/$promptId/diagnose'
    | '/v2/brand-facts/workspace'
    | '/v2/diagnostics/competitor-gap'
    | '/v2/diagnostics/geo-signals'
    | '/v2/diagnostics/perception'
    | '/v2/diagnostics/prompts'
    | '/v2/diagnostics/site-health'
    | '/v2/my-work/content-opportunities'
    | '/v2/my-work/earned-media'
    | '/v2/my-work/queue'
    | '/v2/onboarding/baseline'
    | '/v2/onboarding/baseline-review'
    | '/v2/onboarding/facts'
    | '/v2/onboarding/inspection'
    | '/v2/onboarding/questions'
    | '/v2/onboarding/start'
    | '/v2/settings/billing'
    | '/v2/settings/integrations'
    | '/v2/settings/team'
    | '/v2/visibility/citations'
    | '/v2/visibility/evidence'
    | '/v2/visibility/outcome-review'
    | '/v2/visibility/questions'
    | '/v2/visibility/report'
    | '/v2/visibility/results'
    | '/prompts/$promptId'
    | '/v2/brand-facts'
    | '/v2/diagnostics'
    | '/v2/my-work'
    | '/v2/settings'
    | '/v2/visibility'
    | '/v2/my-work/tasks/$taskId'
    | '/v2/visibility/questions/$questionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/glossary'
    | '/health'
    | '/internal-page'
    | '/pricing'
    | '/privacy'
    | '/v2-preview'
    | '/_app/$'
    | '/_app/act'
    | '/_app/ai-intelligence'
    | '/_app/ai-visibility'
    | '/_app/articles'
    | '/_app/brand-fact-sheet'
    | '/_app/brands'
    | '/_app/citations'
    | '/_app/community'
    | '/_app/competitors'
    | '/_app/content'
    | '/_app/crawler-check'
    | '/_app/dashboard'
    | '/_app/diagnose'
    | '/_app/faq-manager'
    | '/_app/forgot-password'
    | '/_app/geo-analytics'
    | '/_app/geo-signals'
    | '/_app/geo-tools'
    | '/_app/home2'
    | '/_app/keyword-research'
    | '/_app/login'
    | '/_app/monitor'
    | '/_app/opportunities'
    | '/_app/perception'
    | '/_app/prompts'
    | '/_app/register'
    | '/_app/report'
    | '/_app/reset-password'
    | '/_app/settings'
    | '/_app/setup'
    | '/_app/site-health'
    | '/_app/v2'
    | '/_app/verify-email'
    | '/_app/welcome'
    | '/api/$'
    | '/v2-preview/$board'
    | '/webhooks/$'
    | '/v2-preview/'
    | '/_app/admin/scrape'
    | '/_app/content/$articleId'
    | '/_app/prompts/$promptId'
    | '/_app/v2/agency'
    | '/_app/v2/brand-facts'
    | '/_app/v2/diagnostics'
    | '/_app/v2/geo-assistant'
    | '/_app/v2/learn'
    | '/_app/v2/my-work'
    | '/_app/v2/notifications'
    | '/_app/v2/onboarding'
    | '/_app/v2/plans'
    | '/_app/v2/settings'
    | '/_app/v2/sign-in'
    | '/_app/v2/today'
    | '/_app/v2/visibility'
    | '/_app/prompts/'
    | '/_app/admin/scrape/$runId'
    | '/_app/prompts/$promptId/diagnose'
    | '/_app/v2/brand-facts/workspace'
    | '/_app/v2/diagnostics/competitor-gap'
    | '/_app/v2/diagnostics/geo-signals'
    | '/_app/v2/diagnostics/perception'
    | '/_app/v2/diagnostics/prompts'
    | '/_app/v2/diagnostics/site-health'
    | '/_app/v2/my-work/content-opportunities'
    | '/_app/v2/my-work/earned-media'
    | '/_app/v2/my-work/queue'
    | '/_app/v2/onboarding/baseline'
    | '/_app/v2/onboarding/baseline-review'
    | '/_app/v2/onboarding/facts'
    | '/_app/v2/onboarding/inspection'
    | '/_app/v2/onboarding/questions'
    | '/_app/v2/onboarding/start'
    | '/_app/v2/settings/billing'
    | '/_app/v2/settings/integrations'
    | '/_app/v2/settings/team'
    | '/_app/v2/visibility/citations'
    | '/_app/v2/visibility/evidence'
    | '/_app/v2/visibility/outcome-review'
    | '/_app/v2/visibility/questions'
    | '/_app/v2/visibility/report'
    | '/_app/v2/visibility/results'
    | '/_app/prompts/$promptId/'
    | '/_app/v2/brand-facts/'
    | '/_app/v2/diagnostics/'
    | '/_app/v2/my-work/'
    | '/_app/v2/settings/'
    | '/_app/v2/visibility/'
    | '/_app/v2/my-work/tasks/$taskId'
    | '/_app/v2/visibility/questions/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  GlossaryRoute: typeof GlossaryRoute
  HealthRoute: typeof HealthRoute
  InternalPageRoute: typeof InternalPageRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  V2PreviewRoute: typeof V2PreviewRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  WebhooksSplatRoute: typeof WebhooksSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal-page': {
      id: '/internal-page'
      path: '/internal-page'
      fullPath: '/internal-page'
      preLoaderRoute: typeof InternalPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2-preview': {
      id: '/v2-preview'
      path: '/v2-preview'
      fullPath: '/v2-preview'
      preLoaderRoute: typeof V2PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/act': {
      id: '/_app/act'
      path: '/act'
      fullPath: '/act'
      preLoaderRoute: typeof AppActRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-intelligence': {
      id: '/_app/ai-intelligence'
      path: '/ai-intelligence'
      fullPath: '/ai-intelligence'
      preLoaderRoute: typeof AppAiIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-visibility': {
      id: '/_app/ai-visibility'
      path: '/ai-visibility'
      fullPath: '/ai-visibility'
      preLoaderRoute: typeof AppAiVisibilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles': {
      id: '/_app/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AppArticlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brand-fact-sheet': {
      id: '/_app/brand-fact-sheet'
      path: '/brand-fact-sheet'
      fullPath: '/brand-fact-sheet'
      preLoaderRoute: typeof AppBrandFactSheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands': {
      id: '/_app/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AppBrandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/citations': {
      id: '/_app/citations'
      path: '/citations'
      fullPath: '/citations'
      preLoaderRoute: typeof AppCitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitors': {
      id: '/_app/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content': {
      id: '/_app/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crawler-check': {
      id: '/_app/crawler-check'
      path: '/crawler-check'
      fullPath: '/crawler-check'
      preLoaderRoute: typeof AppCrawlerCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnose': {
      id: '/_app/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof AppDiagnoseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faq-manager': {
      id: '/_app/faq-manager'
      path: '/faq-manager'
      fullPath: '/faq-manager'
      preLoaderRoute: typeof AppFaqManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forgot-password': {
      id: '/_app/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/geo-analytics': {
      id: '/_app/geo-analytics'
      path: '/geo-analytics'
      fullPath: '/geo-analytics'
      preLoaderRoute: typeof AppGeoAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/geo-signals': {
      id: '/_app/geo-signals'
      path: '/geo-signals'
      fullPath: '/geo-signals'
      preLoaderRoute: typeof AppGeoSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/geo-tools': {
      id: '/_app/geo-tools'
      path: '/geo-tools'
      fullPath: '/geo-tools'
      preLoaderRoute: typeof AppGeoToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home2': {
      id: '/_app/home2'
      path: '/home2'
      fullPath: '/home2'
      preLoaderRoute: typeof AppHome2RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keyword-research': {
      id: '/_app/keyword-research'
      path: '/keyword-research'
      fullPath: '/keyword-research'
      preLoaderRoute: typeof AppKeywordResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitor': {
      id: '/_app/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof AppMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perception': {
      id: '/_app/perception'
      path: '/perception'
      fullPath: '/perception'
      preLoaderRoute: typeof AppPerceptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prompts': {
      id: '/_app/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reset-password': {
      id: '/_app/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AppResetPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/site-health': {
      id: '/_app/site-health'
      path: '/site-health'
      fullPath: '/site-health'
      preLoaderRoute: typeof AppSiteHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/v2': {
      id: '/_app/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof AppV2RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verify-email': {
      id: '/_app/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AppVerifyEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2-preview/': {
      id: '/v2-preview/'
      path: '/'
      fullPath: '/v2-preview/'
      preLoaderRoute: typeof V2PreviewIndexRouteImport
      parentRoute: typeof V2PreviewRoute
    }
    '/v2-preview/$board': {
      id: '/v2-preview/$board'
      path: '/$board'
      fullPath: '/v2-preview/$board'
      preLoaderRoute: typeof V2PreviewBoardRouteImport
      parentRoute: typeof V2PreviewRoute
    }
    '/webhooks/$': {
      id: '/webhooks/$'
      path: '/webhooks/$'
      fullPath: '/webhooks/$'
      preLoaderRoute: typeof WebhooksSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/scrape': {
      id: '/_app/admin/scrape'
      path: '/admin/scrape'
      fullPath: '/admin/scrape'
      preLoaderRoute: typeof AppAdminScrapeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/$articleId': {
      id: '/_app/content/$articleId'
      path: '/$articleId'
      fullPath: '/content/$articleId'
      preLoaderRoute: typeof AppContentArticleIdRouteImport
      parentRoute: typeof AppContentRoute
    }
    '/_app/prompts/': {
      id: '/_app/prompts/'
      path: '/'
      fullPath: '/prompts/'
      preLoaderRoute: typeof AppPromptsIndexRouteImport
      parentRoute: typeof AppPromptsRoute
    }
    '/_app/prompts/$promptId': {
      id: '/_app/prompts/$promptId'
      path: '/$promptId'
      fullPath: '/prompts/$promptId'
      preLoaderRoute: typeof AppPromptsPromptIdRouteImport
      parentRoute: typeof AppPromptsRoute
    }
    '/_app/v2/agency': {
      id: '/_app/v2/agency'
      path: '/agency'
      fullPath: '/v2/agency'
      preLoaderRoute: typeof AppV2AgencyRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/brand-facts': {
      id: '/_app/v2/brand-facts'
      path: '/brand-facts'
      fullPath: '/v2/brand-facts'
      preLoaderRoute: typeof AppV2BrandFactsRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/diagnostics': {
      id: '/_app/v2/diagnostics'
      path: '/diagnostics'
      fullPath: '/v2/diagnostics'
      preLoaderRoute: typeof AppV2DiagnosticsRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/geo-assistant': {
      id: '/_app/v2/geo-assistant'
      path: '/geo-assistant'
      fullPath: '/v2/geo-assistant'
      preLoaderRoute: typeof AppV2GeoAssistantRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/learn': {
      id: '/_app/v2/learn'
      path: '/learn'
      fullPath: '/v2/learn'
      preLoaderRoute: typeof AppV2LearnRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/my-work': {
      id: '/_app/v2/my-work'
      path: '/my-work'
      fullPath: '/v2/my-work'
      preLoaderRoute: typeof AppV2MyWorkRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/notifications': {
      id: '/_app/v2/notifications'
      path: '/notifications'
      fullPath: '/v2/notifications'
      preLoaderRoute: typeof AppV2NotificationsRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/onboarding': {
      id: '/_app/v2/onboarding'
      path: '/onboarding'
      fullPath: '/v2/onboarding'
      preLoaderRoute: typeof AppV2OnboardingRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/plans': {
      id: '/_app/v2/plans'
      path: '/plans'
      fullPath: '/v2/plans'
      preLoaderRoute: typeof AppV2PlansRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/settings': {
      id: '/_app/v2/settings'
      path: '/settings'
      fullPath: '/v2/settings'
      preLoaderRoute: typeof AppV2SettingsRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/sign-in': {
      id: '/_app/v2/sign-in'
      path: '/sign-in'
      fullPath: '/v2/sign-in'
      preLoaderRoute: typeof AppV2SignInRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/today': {
      id: '/_app/v2/today'
      path: '/today'
      fullPath: '/v2/today'
      preLoaderRoute: typeof AppV2TodayRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/v2/visibility': {
      id: '/_app/v2/visibility'
      path: '/visibility'
      fullPath: '/v2/visibility'
      preLoaderRoute: typeof AppV2VisibilityRouteImport
      parentRoute: typeof AppV2Route
    }
    '/_app/admin/scrape/$runId': {
      id: '/_app/admin/scrape/$runId'
      path: '/$runId'
      fullPath: '/admin/scrape/$runId'
      preLoaderRoute: typeof AppAdminScrapeRunIdRouteImport
      parentRoute: typeof AppAdminScrapeRoute
    }
    '/_app/prompts/$promptId/': {
      id: '/_app/prompts/$promptId/'
      path: '/'
      fullPath: '/prompts/$promptId/'
      preLoaderRoute: typeof AppPromptsPromptIdIndexRouteImport
      parentRoute: typeof AppPromptsPromptIdRoute
    }
    '/_app/prompts/$promptId/diagnose': {
      id: '/_app/prompts/$promptId/diagnose'
      path: '/diagnose'
      fullPath: '/prompts/$promptId/diagnose'
      preLoaderRoute: typeof AppPromptsPromptIdDiagnoseRouteImport
      parentRoute: typeof AppPromptsPromptIdRoute
    }
    '/_app/v2/brand-facts/': {
      id: '/_app/v2/brand-facts/'
      path: '/'
      fullPath: '/v2/brand-facts/'
      preLoaderRoute: typeof AppV2BrandFactsIndexRouteImport
      parentRoute: typeof AppV2BrandFactsRoute
    }
    '/_app/v2/brand-facts/workspace': {
      id: '/_app/v2/brand-facts/workspace'
      path: '/workspace'
      fullPath: '/v2/brand-facts/workspace'
      preLoaderRoute: typeof AppV2BrandFactsWorkspaceRouteImport
      parentRoute: typeof AppV2BrandFactsRoute
    }
    '/_app/v2/diagnostics/': {
      id: '/_app/v2/diagnostics/'
      path: '/'
      fullPath: '/v2/diagnostics/'
      preLoaderRoute: typeof AppV2DiagnosticsIndexRouteImport
      parentRoute: typeof AppV2DiagnosticsRoute
    }
    '/_app/v2/diagnostics/competitor-gap': {
      id: '/_app/v2/diagnostics/competitor-gap'
      path: '/competitor-gap'
      fullPath: '/v2/diagnostics/competitor-gap'
      preLoaderRoute: typeof AppV2DiagnosticsCompetitorGapRouteImport
      parentRoute: typeof AppV2DiagnosticsRoute
    }
    '/_app/v2/diagnostics/geo-signals': {
      id: '/_app/v2/diagnostics/geo-signals'
      path: '/geo-signals'
      fullPath: '/v2/diagnostics/geo-signals'
      preLoaderRoute: typeof AppV2DiagnosticsGeoSignalsRouteImport
      parentRoute: typeof AppV2DiagnosticsRoute
    }
    '/_app/v2/diagnostics/perception': {
      id: '/_app/v2/diagnostics/perception'
      path: '/perception'
      fullPath: '/v2/diagnostics/perception'
      preLoaderRoute: typeof AppV2DiagnosticsPerceptionRouteImport
      parentRoute: typeof AppV2DiagnosticsRoute
    }
    '/_app/v2/diagnostics/prompts': {
      id: '/_app/v2/diagnostics/prompts'
      path: '/prompts'
      fullPath: '/v2/diagnostics/prompts'
      preLoaderRoute: typeof AppV2DiagnosticsPromptsRouteImport
      parentRoute: typeof AppV2DiagnosticsRoute
    }
    '/_app/v2/diagnostics/site-health': {
      id: '/_app/v2/diagnostics/site-health'
      path: '/site-health'
      fullPath: '/v2/diagnostics/site-health'
      preLoaderRoute: typeof AppV2DiagnosticsSiteHealthRouteImport
      parentRoute: typeof AppV2DiagnosticsRoute
    }
    '/_app/v2/my-work/': {
      id: '/_app/v2/my-work/'
      path: '/'
      fullPath: '/v2/my-work/'
      preLoaderRoute: typeof AppV2MyWorkIndexRouteImport
      parentRoute: typeof AppV2MyWorkRoute
    }
    '/_app/v2/my-work/content-opportunities': {
      id: '/_app/v2/my-work/content-opportunities'
      path: '/content-opportunities'
      fullPath: '/v2/my-work/content-opportunities'
      preLoaderRoute: typeof AppV2MyWorkContentOpportunitiesRouteImport
      parentRoute: typeof AppV2MyWorkRoute
    }
    '/_app/v2/my-work/earned-media': {
      id: '/_app/v2/my-work/earned-media'
      path: '/earned-media'
      fullPath: '/v2/my-work/earned-media'
      preLoaderRoute: typeof AppV2MyWorkEarnedMediaRouteImport
      parentRoute: typeof AppV2MyWorkRoute
    }
    '/_app/v2/my-work/queue': {
      id: '/_app/v2/my-work/queue'
      path: '/queue'
      fullPath: '/v2/my-work/queue'
      preLoaderRoute: typeof AppV2MyWorkQueueRouteImport
      parentRoute: typeof AppV2MyWorkRoute
    }
    '/_app/v2/onboarding/baseline': {
      id: '/_app/v2/onboarding/baseline'
      path: '/baseline'
      fullPath: '/v2/onboarding/baseline'
      preLoaderRoute: typeof AppV2OnboardingBaselineRouteImport
      parentRoute: typeof AppV2OnboardingRoute
    }
    '/_app/v2/onboarding/baseline-review': {
      id: '/_app/v2/onboarding/baseline-review'
      path: '/baseline-review'
      fullPath: '/v2/onboarding/baseline-review'
      preLoaderRoute: typeof AppV2OnboardingBaselineReviewRouteImport
      parentRoute: typeof AppV2OnboardingRoute
    }
    '/_app/v2/onboarding/facts': {
      id: '/_app/v2/onboarding/facts'
      path: '/facts'
      fullPath: '/v2/onboarding/facts'
      preLoaderRoute: typeof AppV2OnboardingFactsRouteImport
      parentRoute: typeof AppV2OnboardingRoute
    }
    '/_app/v2/onboarding/inspection': {
      id: '/_app/v2/onboarding/inspection'
      path: '/inspection'
      fullPath: '/v2/onboarding/inspection'
      preLoaderRoute: typeof AppV2OnboardingInspectionRouteImport
      parentRoute: typeof AppV2OnboardingRoute
    }
    '/_app/v2/onboarding/questions': {
      id: '/_app/v2/onboarding/questions'
      path: '/questions'
      fullPath: '/v2/onboarding/questions'
      preLoaderRoute: typeof AppV2OnboardingQuestionsRouteImport
      parentRoute: typeof AppV2OnboardingRoute
    }
    '/_app/v2/onboarding/start': {
      id: '/_app/v2/onboarding/start'
      path: '/start'
      fullPath: '/v2/onboarding/start'
      preLoaderRoute: typeof AppV2OnboardingStartRouteImport
      parentRoute: typeof AppV2OnboardingRoute
    }
    '/_app/v2/settings/': {
      id: '/_app/v2/settings/'
      path: '/'
      fullPath: '/v2/settings/'
      preLoaderRoute: typeof AppV2SettingsIndexRouteImport
      parentRoute: typeof AppV2SettingsRoute
    }
    '/_app/v2/settings/billing': {
      id: '/_app/v2/settings/billing'
      path: '/billing'
      fullPath: '/v2/settings/billing'
      preLoaderRoute: typeof AppV2SettingsBillingRouteImport
      parentRoute: typeof AppV2SettingsRoute
    }
    '/_app/v2/settings/integrations': {
      id: '/_app/v2/settings/integrations'
      path: '/integrations'
      fullPath: '/v2/settings/integrations'
      preLoaderRoute: typeof AppV2SettingsIntegrationsRouteImport
      parentRoute: typeof AppV2SettingsRoute
    }
    '/_app/v2/settings/team': {
      id: '/_app/v2/settings/team'
      path: '/team'
      fullPath: '/v2/settings/team'
      preLoaderRoute: typeof AppV2SettingsTeamRouteImport
      parentRoute: typeof AppV2SettingsRoute
    }
    '/_app/v2/visibility/': {
      id: '/_app/v2/visibility/'
      path: '/'
      fullPath: '/v2/visibility/'
      preLoaderRoute: typeof AppV2VisibilityIndexRouteImport
      parentRoute: typeof AppV2VisibilityRoute
    }
    '/_app/v2/visibility/citations': {
      id: '/_app/v2/visibility/citations'
      path: '/citations'
      fullPath: '/v2/visibility/citations'
      preLoaderRoute: typeof AppV2VisibilityCitationsRouteImport
      parentRoute: typeof AppV2VisibilityRoute
    }
    '/_app/v2/visibility/evidence': {
      id: '/_app/v2/visibility/evidence'
      path: '/evidence'
      fullPath: '/v2/visibility/evidence'
      preLoaderRoute: typeof AppV2VisibilityEvidenceRouteImport
      parentRoute: typeof AppV2VisibilityRoute
    }
    '/_app/v2/visibility/outcome-review': {
      id: '/_app/v2/visibility/outcome-review'
      path: '/outcome-review'
      fullPath: '/v2/visibility/outcome-review'
      preLoaderRoute: typeof AppV2VisibilityOutcomeReviewRouteImport
      parentRoute: typeof AppV2VisibilityRoute
    }
    '/_app/v2/visibility/questions': {
      id: '/_app/v2/visibility/questions'
      path: '/questions'
      fullPath: '/v2/visibility/questions'
      preLoaderRoute: typeof AppV2VisibilityQuestionsRouteImport
      parentRoute: typeof AppV2VisibilityRoute
    }
    '/_app/v2/visibility/report': {
      id: '/_app/v2/visibility/report'
      path: '/report'
      fullPath: '/v2/visibility/report'
      preLoaderRoute: typeof AppV2VisibilityReportRouteImport
      parentRoute: typeof AppV2VisibilityRoute
    }
    '/_app/v2/visibility/results': {
      id: '/_app/v2/visibility/results'
      path: '/results'
      fullPath: '/v2/visibility/results'
      preLoaderRoute: typeof AppV2VisibilityResultsRouteImport
      parentRoute: typeof AppV2VisibilityRoute
    }
    '/_app/v2/my-work/tasks/$taskId': {
      id: '/_app/v2/my-work/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/v2/my-work/tasks/$taskId'
      preLoaderRoute: typeof AppV2MyWorkTasksTaskIdRouteImport
      parentRoute: typeof AppV2MyWorkRoute
    }
    '/_app/v2/visibility/questions/$questionId': {
      id: '/_app/v2/visibility/questions/$questionId'
      path: '/$questionId'
      fullPath: '/v2/visibility/questions/$questionId'
      preLoaderRoute: typeof AppV2VisibilityQuestionsQuestionIdRouteImport
      parentRoute: typeof AppV2VisibilityQuestionsRoute
    }
  }
}

interface AppContentRouteChildren {
  AppContentArticleIdRoute: typeof AppContentArticleIdRoute
}

const AppContentRouteChildren: AppContentRouteChildren = {
  AppContentArticleIdRoute: AppContentArticleIdRoute,
}

const AppContentRouteWithChildren = AppContentRoute._addFileChildren(
  AppContentRouteChildren,
)

interface AppPromptsPromptIdRouteChildren {
  AppPromptsPromptIdDiagnoseRoute: typeof AppPromptsPromptIdDiagnoseRoute
  AppPromptsPromptIdIndexRoute: typeof AppPromptsPromptIdIndexRoute
}

const AppPromptsPromptIdRouteChildren: AppPromptsPromptIdRouteChildren = {
  AppPromptsPromptIdDiagnoseRoute: AppPromptsPromptIdDiagnoseRoute,
  AppPromptsPromptIdIndexRoute: AppPromptsPromptIdIndexRoute,
}

const AppPromptsPromptIdRouteWithChildren =
  AppPromptsPromptIdRoute._addFileChildren(AppPromptsPromptIdRouteChildren)

interface AppPromptsRouteChildren {
  AppPromptsPromptIdRoute: typeof AppPromptsPromptIdRouteWithChildren
  AppPromptsIndexRoute: typeof AppPromptsIndexRoute
}

const AppPromptsRouteChildren: AppPromptsRouteChildren = {
  AppPromptsPromptIdRoute: AppPromptsPromptIdRouteWithChildren,
  AppPromptsIndexRoute: AppPromptsIndexRoute,
}

const AppPromptsRouteWithChildren = AppPromptsRoute._addFileChildren(
  AppPromptsRouteChildren,
)

interface AppV2BrandFactsRouteChildren {
  AppV2BrandFactsWorkspaceRoute: typeof AppV2BrandFactsWorkspaceRoute
  AppV2BrandFactsIndexRoute: typeof AppV2BrandFactsIndexRoute
}

const AppV2BrandFactsRouteChildren: AppV2BrandFactsRouteChildren = {
  AppV2BrandFactsWorkspaceRoute: AppV2BrandFactsWorkspaceRoute,
  AppV2BrandFactsIndexRoute: AppV2BrandFactsIndexRoute,
}

const AppV2BrandFactsRouteWithChildren = AppV2BrandFactsRoute._addFileChildren(
  AppV2BrandFactsRouteChildren,
)

interface AppV2DiagnosticsRouteChildren {
  AppV2DiagnosticsCompetitorGapRoute: typeof AppV2DiagnosticsCompetitorGapRoute
  AppV2DiagnosticsGeoSignalsRoute: typeof AppV2DiagnosticsGeoSignalsRoute
  AppV2DiagnosticsPerceptionRoute: typeof AppV2DiagnosticsPerceptionRoute
  AppV2DiagnosticsPromptsRoute: typeof AppV2DiagnosticsPromptsRoute
  AppV2DiagnosticsSiteHealthRoute: typeof AppV2DiagnosticsSiteHealthRoute
  AppV2DiagnosticsIndexRoute: typeof AppV2DiagnosticsIndexRoute
}

const AppV2DiagnosticsRouteChildren: AppV2DiagnosticsRouteChildren = {
  AppV2DiagnosticsCompetitorGapRoute: AppV2DiagnosticsCompetitorGapRoute,
  AppV2DiagnosticsGeoSignalsRoute: AppV2DiagnosticsGeoSignalsRoute,
  AppV2DiagnosticsPerceptionRoute: AppV2DiagnosticsPerceptionRoute,
  AppV2DiagnosticsPromptsRoute: AppV2DiagnosticsPromptsRoute,
  AppV2DiagnosticsSiteHealthRoute: AppV2DiagnosticsSiteHealthRoute,
  AppV2DiagnosticsIndexRoute: AppV2DiagnosticsIndexRoute,
}

const AppV2DiagnosticsRouteWithChildren =
  AppV2DiagnosticsRoute._addFileChildren(AppV2DiagnosticsRouteChildren)

interface AppV2MyWorkRouteChildren {
  AppV2MyWorkContentOpportunitiesRoute: typeof AppV2MyWorkContentOpportunitiesRoute
  AppV2MyWorkEarnedMediaRoute: typeof AppV2MyWorkEarnedMediaRoute
  AppV2MyWorkQueueRoute: typeof AppV2MyWorkQueueRoute
  AppV2MyWorkIndexRoute: typeof AppV2MyWorkIndexRoute
  AppV2MyWorkTasksTaskIdRoute: typeof AppV2MyWorkTasksTaskIdRoute
}

const AppV2MyWorkRouteChildren: AppV2MyWorkRouteChildren = {
  AppV2MyWorkContentOpportunitiesRoute: AppV2MyWorkContentOpportunitiesRoute,
  AppV2MyWorkEarnedMediaRoute: AppV2MyWorkEarnedMediaRoute,
  AppV2MyWorkQueueRoute: AppV2MyWorkQueueRoute,
  AppV2MyWorkIndexRoute: AppV2MyWorkIndexRoute,
  AppV2MyWorkTasksTaskIdRoute: AppV2MyWorkTasksTaskIdRoute,
}

const AppV2MyWorkRouteWithChildren = AppV2MyWorkRoute._addFileChildren(
  AppV2MyWorkRouteChildren,
)

interface AppV2OnboardingRouteChildren {
  AppV2OnboardingBaselineRoute: typeof AppV2OnboardingBaselineRoute
  AppV2OnboardingBaselineReviewRoute: typeof AppV2OnboardingBaselineReviewRoute
  AppV2OnboardingFactsRoute: typeof AppV2OnboardingFactsRoute
  AppV2OnboardingInspectionRoute: typeof AppV2OnboardingInspectionRoute
  AppV2OnboardingQuestionsRoute: typeof AppV2OnboardingQuestionsRoute
  AppV2OnboardingStartRoute: typeof AppV2OnboardingStartRoute
}

const AppV2OnboardingRouteChildren: AppV2OnboardingRouteChildren = {
  AppV2OnboardingBaselineRoute: AppV2OnboardingBaselineRoute,
  AppV2OnboardingBaselineReviewRoute: AppV2OnboardingBaselineReviewRoute,
  AppV2OnboardingFactsRoute: AppV2OnboardingFactsRoute,
  AppV2OnboardingInspectionRoute: AppV2OnboardingInspectionRoute,
  AppV2OnboardingQuestionsRoute: AppV2OnboardingQuestionsRoute,
  AppV2OnboardingStartRoute: AppV2OnboardingStartRoute,
}

const AppV2OnboardingRouteWithChildren = AppV2OnboardingRoute._addFileChildren(
  AppV2OnboardingRouteChildren,
)

interface AppV2SettingsRouteChildren {
  AppV2SettingsBillingRoute: typeof AppV2SettingsBillingRoute
  AppV2SettingsIntegrationsRoute: typeof AppV2SettingsIntegrationsRoute
  AppV2SettingsTeamRoute: typeof AppV2SettingsTeamRoute
  AppV2SettingsIndexRoute: typeof AppV2SettingsIndexRoute
}

const AppV2SettingsRouteChildren: AppV2SettingsRouteChildren = {
  AppV2SettingsBillingRoute: AppV2SettingsBillingRoute,
  AppV2SettingsIntegrationsRoute: AppV2SettingsIntegrationsRoute,
  AppV2SettingsTeamRoute: AppV2SettingsTeamRoute,
  AppV2SettingsIndexRoute: AppV2SettingsIndexRoute,
}

const AppV2SettingsRouteWithChildren = AppV2SettingsRoute._addFileChildren(
  AppV2SettingsRouteChildren,
)

interface AppV2VisibilityQuestionsRouteChildren {
  AppV2VisibilityQuestionsQuestionIdRoute: typeof AppV2VisibilityQuestionsQuestionIdRoute
}

const AppV2VisibilityQuestionsRouteChildren: AppV2VisibilityQuestionsRouteChildren =
  {
    AppV2VisibilityQuestionsQuestionIdRoute:
      AppV2VisibilityQuestionsQuestionIdRoute,
  }

const AppV2VisibilityQuestionsRouteWithChildren =
  AppV2VisibilityQuestionsRoute._addFileChildren(
    AppV2VisibilityQuestionsRouteChildren,
  )

interface AppV2VisibilityRouteChildren {
  AppV2VisibilityCitationsRoute: typeof AppV2VisibilityCitationsRoute
  AppV2VisibilityEvidenceRoute: typeof AppV2VisibilityEvidenceRoute
  AppV2VisibilityOutcomeReviewRoute: typeof AppV2VisibilityOutcomeReviewRoute
  AppV2VisibilityQuestionsRoute: typeof AppV2VisibilityQuestionsRouteWithChildren
  AppV2VisibilityReportRoute: typeof AppV2VisibilityReportRoute
  AppV2VisibilityResultsRoute: typeof AppV2VisibilityResultsRoute
  AppV2VisibilityIndexRoute: typeof AppV2VisibilityIndexRoute
}

const AppV2VisibilityRouteChildren: AppV2VisibilityRouteChildren = {
  AppV2VisibilityCitationsRoute: AppV2VisibilityCitationsRoute,
  AppV2VisibilityEvidenceRoute: AppV2VisibilityEvidenceRoute,
  AppV2VisibilityOutcomeReviewRoute: AppV2VisibilityOutcomeReviewRoute,
  AppV2VisibilityQuestionsRoute: AppV2VisibilityQuestionsRouteWithChildren,
  AppV2VisibilityReportRoute: AppV2VisibilityReportRoute,
  AppV2VisibilityResultsRoute: AppV2VisibilityResultsRoute,
  AppV2VisibilityIndexRoute: AppV2VisibilityIndexRoute,
}

const AppV2VisibilityRouteWithChildren = AppV2VisibilityRoute._addFileChildren(
  AppV2VisibilityRouteChildren,
)

interface AppV2RouteChildren {
  AppV2AgencyRoute: typeof AppV2AgencyRoute
  AppV2BrandFactsRoute: typeof AppV2BrandFactsRouteWithChildren
  AppV2DiagnosticsRoute: typeof AppV2DiagnosticsRouteWithChildren
  AppV2GeoAssistantRoute: typeof AppV2GeoAssistantRoute
  AppV2LearnRoute: typeof AppV2LearnRoute
  AppV2MyWorkRoute: typeof AppV2MyWorkRouteWithChildren
  AppV2NotificationsRoute: typeof AppV2NotificationsRoute
  AppV2OnboardingRoute: typeof AppV2OnboardingRouteWithChildren
  AppV2PlansRoute: typeof AppV2PlansRoute
  AppV2SettingsRoute: typeof AppV2SettingsRouteWithChildren
  AppV2SignInRoute: typeof AppV2SignInRoute
  AppV2TodayRoute: typeof AppV2TodayRoute
  AppV2VisibilityRoute: typeof AppV2VisibilityRouteWithChildren
}

const AppV2RouteChildren: AppV2RouteChildren = {
  AppV2AgencyRoute: AppV2AgencyRoute,
  AppV2BrandFactsRoute: AppV2BrandFactsRouteWithChildren,
  AppV2DiagnosticsRoute: AppV2DiagnosticsRouteWithChildren,
  AppV2GeoAssistantRoute: AppV2GeoAssistantRoute,
  AppV2LearnRoute: AppV2LearnRoute,
  AppV2MyWorkRoute: AppV2MyWorkRouteWithChildren,
  AppV2NotificationsRoute: AppV2NotificationsRoute,
  AppV2OnboardingRoute: AppV2OnboardingRouteWithChildren,
  AppV2PlansRoute: AppV2PlansRoute,
  AppV2SettingsRoute: AppV2SettingsRouteWithChildren,
  AppV2SignInRoute: AppV2SignInRoute,
  AppV2TodayRoute: AppV2TodayRoute,
  AppV2VisibilityRoute: AppV2VisibilityRouteWithChildren,
}

const AppV2RouteWithChildren = AppV2Route._addFileChildren(AppV2RouteChildren)

interface AppAdminScrapeRouteChildren {
  AppAdminScrapeRunIdRoute: typeof AppAdminScrapeRunIdRoute
}

const AppAdminScrapeRouteChildren: AppAdminScrapeRouteChildren = {
  AppAdminScrapeRunIdRoute: AppAdminScrapeRunIdRoute,
}

const AppAdminScrapeRouteWithChildren = AppAdminScrapeRoute._addFileChildren(
  AppAdminScrapeRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppActRoute: typeof AppActRoute
  AppAiIntelligenceRoute: typeof AppAiIntelligenceRoute
  AppAiVisibilityRoute: typeof AppAiVisibilityRoute
  AppArticlesRoute: typeof AppArticlesRoute
  AppBrandFactSheetRoute: typeof AppBrandFactSheetRoute
  AppBrandsRoute: typeof AppBrandsRoute
  AppCitationsRoute: typeof AppCitationsRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppContentRoute: typeof AppContentRouteWithChildren
  AppCrawlerCheckRoute: typeof AppCrawlerCheckRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiagnoseRoute: typeof AppDiagnoseRoute
  AppFaqManagerRoute: typeof AppFaqManagerRoute
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppGeoAnalyticsRoute: typeof AppGeoAnalyticsRoute
  AppGeoSignalsRoute: typeof AppGeoSignalsRoute
  AppGeoToolsRoute: typeof AppGeoToolsRoute
  AppHome2Route: typeof AppHome2Route
  AppKeywordResearchRoute: typeof AppKeywordResearchRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMonitorRoute: typeof AppMonitorRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppPerceptionRoute: typeof AppPerceptionRoute
  AppPromptsRoute: typeof AppPromptsRouteWithChildren
  AppRegisterRoute: typeof AppRegisterRoute
  AppReportRoute: typeof AppReportRoute
  AppResetPasswordRoute: typeof AppResetPasswordRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSetupRoute: typeof AppSetupRoute
  AppSiteHealthRoute: typeof AppSiteHealthRoute
  AppV2Route: typeof AppV2RouteWithChildren
  AppVerifyEmailRoute: typeof AppVerifyEmailRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppAdminScrapeRoute: typeof AppAdminScrapeRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppActRoute: AppActRoute,
  AppAiIntelligenceRoute: AppAiIntelligenceRoute,
  AppAiVisibilityRoute: AppAiVisibilityRoute,
  AppArticlesRoute: AppArticlesRoute,
  AppBrandFactSheetRoute: AppBrandFactSheetRoute,
  AppBrandsRoute: AppBrandsRoute,
  AppCitationsRoute: AppCitationsRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppContentRoute: AppContentRouteWithChildren,
  AppCrawlerCheckRoute: AppCrawlerCheckRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiagnoseRoute: AppDiagnoseRoute,
  AppFaqManagerRoute: AppFaqManagerRoute,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppGeoAnalyticsRoute: AppGeoAnalyticsRoute,
  AppGeoSignalsRoute: AppGeoSignalsRoute,
  AppGeoToolsRoute: AppGeoToolsRoute,
  AppHome2Route: AppHome2Route,
  AppKeywordResearchRoute: AppKeywordResearchRoute,
  AppLoginRoute: AppLoginRoute,
  AppMonitorRoute: AppMonitorRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppPerceptionRoute: AppPerceptionRoute,
  AppPromptsRoute: AppPromptsRouteWithChildren,
  AppRegisterRoute: AppRegisterRoute,
  AppReportRoute: AppReportRoute,
  AppResetPasswordRoute: AppResetPasswordRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSetupRoute: AppSetupRoute,
  AppSiteHealthRoute: AppSiteHealthRoute,
  AppV2Route: AppV2RouteWithChildren,
  AppVerifyEmailRoute: AppVerifyEmailRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppAdminScrapeRoute: AppAdminScrapeRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface V2PreviewRouteChildren {
  V2PreviewBoardRoute: typeof V2PreviewBoardRoute
  V2PreviewIndexRoute: typeof V2PreviewIndexRoute
}

const V2PreviewRouteChildren: V2PreviewRouteChildren = {
  V2PreviewBoardRoute: V2PreviewBoardRoute,
  V2PreviewIndexRoute: V2PreviewIndexRoute,
}

const V2PreviewRouteWithChildren = V2PreviewRoute._addFileChildren(
  V2PreviewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  GlossaryRoute: GlossaryRoute,
  HealthRoute: HealthRoute,
  InternalPageRoute: InternalPageRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  V2PreviewRoute: V2PreviewRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  WebhooksSplatRoute: WebhooksSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
