import type { Board40Data } from "./Screen";

export const board40Fixture: Board40Data = {
  brandId: "brand-venture-pr",
  mode: "expert",
  counts: { all: 4, listicle: 1, community: 1, mention: 1, citation: 1 },
  outreachCounts: { notStarted: 3, inProgress: 1, completed: 0, notFit: 0 },
  opportunities: [
    {
      id: "listicle:techcrunch-best-pr",
      sourceType: "listicle",
      sourceTypeLabel: "Listicle mention",
      sourceName: "TechCrunch",
      sourceUrl: "https://techcrunch.test/best-startup-pr-agencies",
      topicMatch: "High",
      affectedQuestionCount: 3,
      relationship: "No contact",
      evidenceType: "Citation gap",
      effort: "Medium",
      confidence: "High",
      status: "Not started",
      canUpdateStatus: true,
      detail: {
        headline:
          '"Best startup PR agencies" ranks a "best of" list on TechCrunch and does not include the brand.',
        quote: null,
        quoteAttribution: null,
        observedAt: "2026-09-05T00:00:00.000Z",
      },
    },
    {
      id: "community:reddit-startups",
      sourceType: "community",
      sourceTypeLabel: "Community discussion",
      sourceName: "r/startups (reddit)",
      sourceUrl: "https://reddit.test/r/startups",
      topicMatch: "Medium",
      affectedQuestionCount: 2,
      relationship: "No contact",
      evidenceType: "Question thread",
      effort: "Low",
      confidence: "Medium",
      status: "In progress",
      canUpdateStatus: true,
      detail: {
        headline:
          "A draft reddit post for r/startups has content and a target group ready to complete.",
        quote: "Startup PR pricing usually depends on scope, not a flat monthly fee.",
        quoteAttribution: "reddit · r/startups",
        observedAt: "2026-09-02T00:00:00.000Z",
      },
    },
    {
      id: "mention:g2-thread",
      sourceType: "mention",
      sourceTypeLabel: "Existing mention",
      sourceName: "G2 review thread",
      sourceUrl: "https://g2.test/reviews/venturepr",
      topicMatch: "Low",
      affectedQuestionCount: 1,
      relationship: "Warm contact",
      evidenceType: "Existing mention",
      effort: "Low",
      confidence: "High",
      status: "Not started",
      canUpdateStatus: true,
      detail: {
        headline:
          'G2 already mentioned the brand in "PR software comparison". Deepen it into full coverage.',
        quote: "VenturePR came up as a solid option for startup pricing questions.",
        quoteAttribution: "G2",
        observedAt: "2026-09-04T00:00:00.000Z",
      },
    },
    {
      id: "citation:saastr.test",
      sourceType: "citation",
      sourceTypeLabel: "AI-cited source",
      sourceName: "saastr.test",
      sourceUrl: "https://saastr.test",
      topicMatch: "Medium",
      affectedQuestionCount: 2,
      relationship: "No contact",
      evidenceType: "Citation gap",
      effort: "Medium",
      confidence: "Medium",
      status: "Not started",
      canUpdateStatus: false,
      detail: {
        headline:
          "AI answers for tracked buyer questions cite saastr.test while leaving the brand out.",
        quote: "Several PR vendors were compared for their pricing transparency.",
        quoteAttribution: "chatgpt, checked 2026-09-08",
        observedAt: "2026-09-08T00:00:00.000Z",
      },
    },
  ],
};
