// Vercel function entry — single function handles all /api/* routes plus
// /health and /webhooks/* (per the rewrites in vercel.json). Imports a
// self-contained pre-bundled Express app produced by our build step
// (see package.json's `build` script). Pre-bundling sidesteps Vercel's
// node-file-trace, which doesn't follow extensionless ESM imports
// through our server/ tree.

// @ts-expect-error — bundle is generated by the build step before deploy
import { app, prepareApp } from "./_bundle.js";

import type { IncomingMessage, ServerResponse } from "http";

const ready = prepareApp();

export default async function handler(req: IncomingMessage, res: ServerResponse): Promise<void> {
  await ready;
  return app(req, res);
}
