// Vercel function entry. The real handler lives in api/_bundle.js,
// produced by the build step from server/vercelEntry.ts (see
// package.json `build`). Pre-bundling sidesteps Vercel's
// node-file-trace, which doesn't follow extensionless ESM imports
// through our server/ tree.

// @ts-expect-error — bundle is generated by the build step before deploy
export { default } from "./_bundle.js";
